import { fetchSpeakersFromSheet } from "@/app/actions/google-sheets"

export interface Speaker {
  slug: string
  name: string
  title: string
  image: string
  imagePosition?: string // Add this new optional property
  bio: string
  programs: string[]
  fee: string
  location: string
  linkedin?: string
  website?: string
  email: string
  contact: string
  listed: boolean
  expertise: string[]
  industries: string[]
  ranking: number // New ranking field (1-100, higher = more prominent)
}

// Local fallback data (existing 'speakers' array)
const localSpeakers: Speaker[] = [
  {
    slug: "adam-cheyer",
    name: "Adam Cheyer",
    title:
      "VP of AI Experience at Airbnb, Co-Founder of Siri, Gameplanner.ai, Viv Labs, Sentient, and Founding Member of Change.org",
    image: "/speakers/adam-cheyer-headshot.png",
    imagePosition: "top",
    bio: "Adam is an expert in entrepreneurship, artificial intelligence, and scaling startups. With over ten years of experience founding and exiting companies, he was a co-founder of Siri, which Apple acquired, co-founded Viv Labs, which was acquired by Samsung, and Gameplanner.AI, which was Airbnb's first acquisition since going public. Through Siri and Bixby (Apple & Samsung's voice assistants), Adam has created key technology in over 1.5 billion devices. A founding developer of Change.org, he's helped unite 500M+ members to create social change across the globe. After his most recent acquisition, he leads all AI efforts at Airbnb as the VP of AI Experience.\n\nAdam is a 30+ year veteran in Artificial Intelligence, initially starting as a researcher at SRI International. With 39 patents and 60+ publications, his technical expertise and visionary approach to entrepreneurship are widely recognized across the globe. Before Siri, he co-founded Sentient Technologies, which applies distributed machine learning algorithms to discover novel solutions to complex problems.\n\nBeyond his success in technology, Adam is also an award-winning magician. He's performed on some of the most prestigious stages in magic, including the Magic Castle in Los Angeles and the hit TV show \"Penn and Teller Fool Us.\" As a bonus, Adam usually includes a magic trick as a way to entertain and delight during his keynotes.",
    programs: [
      "ChatGPT and The Rise of Conversational AI",
      "The Future of AI and Businesses",
      '"Hey SIRI": A Founding Story',
    ],
    fee: "Please Inquire",
    location: "San Franscisco, California",
    linkedin: "https://www.linkedin.com/in/adamcheyer/",
    website: "http://adam.cheyer.com/site/home",
    email: "adam.cheyer@gmail.com",
    contact: "Direct",
    listed: true,
    expertise: ["Conversational AI", "Virtual Assistants", "Voice Technology", "AI Product Development"],
    industries: ["Technology", "Consumer Electronics", "Mobile"],
    ranking: 99,
  },
  {
    slug: "peter-norvig",
    name: "Peter Norvig",
    title: "Former Head of Computational Science at NASA and Director of Research and Search Quality at Google",
    image: "/speakers/peter-norvig-headshot.jpg",
    bio: 'Peter Norvig, a distinguished American computer scientist, is widely recognized for his profound contributions to artificial intelligence and education. As a Distinguished Education Fellow at the Stanford Institute for Human-Centered AI and a former director at Google, Norvig has been instrumental in shaping the field of AI. His co-authorship of "Artificial Intelligence: A Modern Approach," the most widely used textbook in AI, used in over 1,500 universities worldwide, highlights his academic influence.\n\nNorvig\'s career spans various pivotal roles, including leading the Computational Sciences Division at NASA Ames Research Center and contributing to advancements at companies like Junglee and Sun Microsystems Laboratories. His academic tenure includes positions at the University of Southern California and Berkeley, enhancing his reputation as a scholar and educator. His publications in AI, natural language processing, and information retrieval, notably "Paradigms of AI Programming" and "Intelligent Help Systems for UNIX," have been seminal in the field.\n\nA pioneer in online education, Norvig\'s collaboration with Sebastian Thrun to develop an online AI course attracted over 160,000 students, demonstrating his commitment to accessible, high-quality education. His influential publications, like the "Teach Yourself Programming in Ten Years" article and "The Unreasonable Effectiveness of Data," have significantly impacted how we understand programming and data\'s role in AI.\n\nAs a sought-after speaker, Norvig has shared his expertise globally, including notable presentations for the University of British Columbia and in his TED Talk. His work has not only advanced the technical aspects of AI but also its educational and ethical dimensions. Peter Norvig remains a pivotal figure in AI, influencing academic circles and the broader public understanding of this transformative technology.',
    programs: [
      "The Pursuit of Machine Learning",
      "The Crossroads Between AI and Space",
      "The Challenge & Promise of Artificial Intelligence",
    ],
    fee: "$25k to $50k plus travel",
    location: "California, United States",
    linkedin: "https://www.linkedin.com/in/pnorvig/",
    website: "https://norvig.com/",
    email: "peter@norvig.com",
    contact: "Direct",
    listed: true,
    expertise: ["Artificial Intelligence", "Machine Learning", "Search Algorithms", "AI Education"],
    industries: ["Technology", "Education", "Research"],
    ranking: 100,
  },
  {
    slug: "cassie-kozyrkov",
    name: "Cassie Kozyrkov",
    title: "CEO of Kozyr, AI Luminary, Former Chief Decision Scientist at Google, and Pioneer of Decision Intelligence",
    image: "/speakers/cassie-kozyrkov-headshot.jpg",
    imagePosition: "top",
    bio: "Cassie Kozyrkov, CEO of Kozyr, is a renowned leader in artificial intelligence. She is best known for founding the field of Decision Intelligence and serving as Google's first Chief Decision Scientist, where she spearheaded Google's transformation into an AI-first company.\n\nToday, Cassie is a sought-after AI advisor and speaker who has transformed how organizations like Gucci, NASA, Spotify, Meta, and GSK approach AI strategy. Passionate about elevating human potential through the responsible adoption of complex technology, she also serves on the Innovation Advisory Council of the Federal Reserve Bank of New York and an investor in emerging product companies.\n\nHer influence on Google's culture is legendary; no matter how big the auditorium, Google had to use lotteries to manage the demand to participate in one of her live workshops. Her work, which included personally training over 20,000 Googlers in AI and data-driven decision-making, impacted more than 500 company initiatives.\n\nCombining deep technical knowledge with theater-trained charisma, Cassie is a captivating keynote speaker with the rare ability to make complex concepts accessible, engaging, and actionable for executive and general audiences alike. Her humor, wit, and vivid analogies ensure that people of all stripes leave her talks inspired and equipped to drive innovation. Cassie has delighted live audiences in more than 40 countries and on all seven continents, including stages at the United Nations, World Economic Forum, Web Summit, and SXSW.\n\nCassie has appeared on the cover of Forbes AI and featured in Harvard Business Review, Fortune, Fast Company, WIRED, Success, Entrepreneur, as well as a recent documentary on the AI revolution. Her online courses and more than 200+ published articles have reached millions and cemented her position as a LinkedIn Top Voice and the #1 Writer in AI on Medium for many years. She is followed by more than 24,000 CxOs.\n\nHailing from South Africa, Cassie began her undergraduate studies at the age of 15 at Nelson Mandela University and earned degrees in economics, mathematical statistics, psychology and neuroscience from the University of Chicago, NCSU, and Duke University, which honored her as a Few-Glasson Distinguished Alumna for her significant contributions to the fields of AI and Decision Intelligence.",
    programs: [
      "The Future is AI-First: Are You Ready to Lead?",
      "AI Won't Steal Your Job, But It Will Steal Your Excuses",
      "Why Businesses Fail at AI Adoption: From Buzzwords to Business Strategy",
      "Mind The Gap: Digital Trust Habits For The AI Era",
    ],
    fee: "Please Inquire",
    location: "Miami, Florida",
    linkedin: "https://www.linkedin.com/in/kozyrkov/",
    website: "https://kozyr.com/",
    email: "speaking@kozyr.com",
    contact: "Peter",
    listed: true,
    expertise: ["AI Strategy", "Decision Intelligence", "Data Science", "Business AI"],
    industries: ["Technology", "Finance", "Healthcare", "Consulting"],
    ranking: 92,
  },
  {
    slug: "rana-el-kaliouby",
    name: "Rana el Kaliouby",
    title:
      "Co-Founder and General Partner of Blue Tulip Ventures, Former Deputy CEO of Smart Eye, Co-Founder of Affectiva, and Author",
    image: "/speakers/rana-el-kaliouby-headshot.jpg",
    imagePosition: "top",
    bio: "Rana el Kaliouby is a distinguished figure in the realm of emotion AI, renowned for her groundbreaking work in bringing emotional intelligence to technology. Born and raised in Cairo, Egypt, she embarked on an academic journey that led her to earn her bachelor's and master's degrees from the American University in Cairo and a Ph.D. from Newnham College, Cambridge. \n\nRana's career began with a pivotal role at the MIT Media Lab's Affective Computing group where she was integral to the team that developed the innovative \"emotional hearing aid,\" a pioneering set of emotion-reading wearable glasses. This invention gained recognition as one of the New York Times' Top 100 Innovations of 2006. \n\nHer vision for humanizing technology led her to co-found Affectiva, a spin-off from the MIT Media Lab. As the CEO of Affectiva, Rana has been at the forefront of leveraging facial and vocal recognition software to bridge the gap between humans and machines. Under her leadership, Affectiva has grown its facial emotion repository to nearly 6 million faces analyzed across 75 countries. \n\nBeyond her role in Affectiva, Rana has made her mark as a World Economic Forum Young Global Leader. She has also co-hosted the PBS NOVA Wonders series, further demonstrating her ability to make complex technological concepts accessible to a wider audience. \n\nRana's journey and insights into the world of AI and emotion recognition are eloquently captured in her memoir, \"Girl Decoded.\" Additionally, she has contributed a chapter to \"Architects of Intelligence: The Truth About AI from the People Building It\" by Martin Ford, solidifying her position as a thought leader in the AI community.",
    programs: ["The Ethics Behind Smarter AI", "The Future of Emotional AI"],
    fee: "Please Inquire",
    location: "Boston, MA",
    linkedin: "https://www.linkedin.com/in/kaliouby/",
    website: "https://smarteye.ai/",
    email: "kaliouby@smarteye.ai",
    contact: "Adam",
    listed: true,
    expertise: ["Emotion AI", "Computer Vision", "Facial Recognition", "AI Startups"],
    industries: ["Automotive", "Healthcare", "Advertising", "Technology"],
    ranking: 90,
  },
  {
    slug: "allie-k-miller",
    name: "Allie Miller",
    title: "Former Global Head of Machine Learning For Startups and Venture Capital at Amazon (AWS)",
    image: "/speakers/allie-k-miller-fireside.jpg",
    bio: "Allie K. Miller stands out as a preeminent leader in artificial intelligence, merging her roles as an advisor, investor, and influencer in the AI sphere. Her journey includes a pivotal role as the Global Head of Machine Learning Business Development for Startups and Venture Capital at Amazon (AWS), where she not only advised world-leading ML researchers and founders but also transformed her division into a 100-person, 10-figure organization. Prior to Amazon, Allie was the youngest-ever woman at IBM to spearhead the development of an AI product, impacting thousands of companies across domains like computer vision and data regulation.\n\nBeyond her corporate achievements, Allie is a formidable force in shaping the AI landscape. She has addressed global platforms, including the European Commission, and has authored over 10 guidebooks on AI, focusing on empowering businesses to harness AI successfully. Her contributions to AI have earned her numerous accolades, including AIconic's \"AI Innovator of the Year\" in 2019, LinkedIn Top Voice for Technology and AI for five consecutive years, and recognition by Award Magazine, Chief in Tech, and ReadWrite as a leading woman in tech and a global thought leader.\n\nAllie's commitment extends to promoting diversity and education in AI, as evidenced by her founding The AI Pipeline and co-founding Girls of the Future. She also serves as a national ambassador for AAAS and an ambassador for Advancing Women in Product. Her investment acumen is showcased through her role as an angel investor in machine learning startups and winning the Grand Prize in three national innovation competitions.\n\nHolding a double-major MBA from The Wharton School and a BA in Cognitive Science from Dartmouth College, Allie's academic background is as impressive as her professional journey. Her expertise in cognitive science, encompassing computer science, linguistics, and psychology, complements her extensive practical experience in the field of artificial intelligence. Allie K. Miller represents the epitome of innovation, leadership, and advocacy in the rapidly evolving world of AI.",
    programs: ["The Future of AI"],
    fee: "Please Inquire",
    location: "New York City, New York",
    linkedin: "https://www.linkedin.com/in/alliekmiller/",
    website: "https://alliekmiller.com/",
    email: "hello@alliekmiller.com",
    contact: "Adam",
    listed: true,
    expertise: ["AI Strategy", "Machine Learning", "Business Development", "AI Diversity"],
    industries: ["Technology", "Finance", "Retail", "Healthcare"],
    ranking: 88,
  },
  {
    slug: "dag-kittlaus",
    name: "Dag Kittlaus",
    title: "Former Co-Founder of Siri and Viv Labs, Co-founder/CEO of Riva Health",
    image: "/speakers/dag-kittlaus-headshot.jpg",
    bio: "Dag Kittlaus is a visionary entrepreneur and a leading figure in the AI industry, renowned as the co-founder and CEO of Viv, acquired by Samsung in 2016, and the groundbreaking Siri, which was acquired by Apple in 2010. Now, he's a co-founder and CEO of Riva a med-tech company dedicated to using mobile technology and AI to improve hypertension management drastically. His journey in technology began as an Entrepreneur-in-Residence at SRI, leading to the creation of Siri, the world's first virtual personal assistant. Following the acquisition of Siri by Apple, Dag served as the Director of iPhone Apps, overseeing the Siri and speech recognition teams, before launching Viv in 2012, an ambitious project aiming to democratize AI and enable seamless interaction with technology.\n\nWith over a decade of experience in consumer wireless internet both in Scandinavia and the US, Dag's career is a testament to his innovative spirit and leadership skills. He held key roles at Telenor Mobile as VP of Consumer Internet Services and at Motorola, where he was the General Manager of xProducts and founder and GM of Motorola's Interactive Media Group. His work at Motorola led to the creation and launch of Screen3, a pioneering consumer mobile application widely used and adopted by major telecom companies.",
    programs: ["Past, Present, and Future of AI", "How To Sell The Vision of AI", "AI in Healthcare"],
    fee: "Please Inquire",
    location: "Chicago, Illinois",
    email: "dag@sirifounder.com",
    contact: "Direct",
    listed: true,
    expertise: ["Conversational AI", "AI Entrepreneurship", "Voice Technology", "AI Innovation"],
    industries: ["Technology", "Startups", "AI", "Consumer Electronics"],
    ranking: 85,
  },
  {
    slug: "luc-julia",
    name: "Dr. Luc Julia",
    title: "Chief Scientific Officer for Renault",
    image: "/placeholder.svg?height=400&width=400",
    bio: 'Dr. Luc JULIA, Chief Scientific Officer for Renault, was CTO and Senior Vice President of Innovation for Samsung Electronics, directed Siri at Apple, was Chief Technologist at Hewlett-Packard and cofounded a number of start-ups in the Silicon Valley. While conducting research at SRI International, he was involved in the creation of Nuance Communications, now the world leader in speech recognition.\n\nRecipient of Légion d\'Honneur, the highest order of France, and member of its National Academy of Technologies, he holds degrees in Mathematics and Computer Science from the University Pierre et Marie Curie in Paris and earned a Ph.D. in Computer Science at the Ecole Nationale Supérieure des Télécommunications de Paris.\n\nHe is the bestselling author of the book "There is no such thing as Artificial Intelligence", holds dozens of patents and is recognized as one of the top 100 most influential French developers in the digital world.',
    programs: ["There is no such thing as Artificial Intelligence", "Generative AI: Myth and Reality"],
    fee: "Please Inquire",
    location: "Bay Area, California & Paris, France",
    email: "luc@siricocreator.com",
    contact: "Direct",
    listed: true,
    expertise: ["Conversational AI", "Voice Technology", "AI Innovation", "Natural Language Processing"],
    industries: ["Technology", "AI", "Consumer Electronics", "Innovation"],
    ranking: 83,
  },
  {
    slug: "charlene-li",
    name: "Charlene Li",
    title: "Author, Advisor, and Executive Coach",
    image: "/speakers/charlene-li-headshot.jpg",
    bio: "For the past two decades, Charlene Li has been helping people see the future. With a focus on digital transformation, disruption leadership and strategy, customer experience, and the future of work, she has positioned herself as a pivotal figure helping corporations navigate the modern business landscape. She's the author of six books, including the New York Times bestseller Open Leadership and the critically acclaimed Groundswell, co-authored by her. Her most recent publication, The Disruption Mindset, has also achieved bestseller status, and she is currently working on a new book titled Winning with Generative AI.\n\nCharlene Li's career is marked by her entrepreneurial spirit, as she founded Altimeter, a disruptive analyst firm that was later acquired in 2015. Her tenure as the Chief Research Officer for PA Consulting showcased her ability to lead thought leadership programs with acumen. Presently, she heads Quantum Networks Group, leveraging her extensive experience to guide companies through the digital era. Her advisory role spans a wide spectrum of industries, having worked with hundreds of leading companies, including Adobe and Southwest Airlines, and providing insights to 49 of the Fortune 100 companies.\n\nCharlene Li's academic achievements include graduating magna cum laude from Harvard College and earning an MBA from Harvard Business Business School. Residing in San Francisco, she enjoys the personal challenge of teaching her cat tricks in her time off. The blend of professional achievement, thought leadership, and personal interests highlights Charlene Li's diverse talents and contributions to the business world and beyond.",
    programs: [
      "Winning With Generative AI: Crafting a Future-Ready Strategy",
      "Creating a Unified Generative AI Strategy: An Executive Roadmap",
      "Strategizing Generative AI: Vision, Alignment, and Execution",
    ],
    fee: "$30,000 to $55,000 plus travel.",
    location: "San Francisco, California",
    linkedin: "https://www.linkedin.com/in/charleneli/",
    website: "https://charleneli.com/",
    email: "charlene@charleneli.com",
    contact: "Jeremiah Owyang",
    listed: true,
    expertise: ["Digital Transformation", "AI Leadership", "Future of Work", "Technology Strategy"],
    industries: ["Technology", "Finance", "Consulting", "Media"],
    ranking: 80,
  },
  {
    slug: "ashley-tarver",
    name: "Ashley Tarver",
    title: "Data & AI Cloud Evangelist at Microsoft",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Ashley Tarver is a leading AI technology evangelist and entrepreneur who works with Microsoft's largest Silicon Valley customers to shape the future of artificial intelligence implementation. As a trusted advisor to senior executives, he guides Fortune 500 companies in deploying AI and machine learning solutions across diverse industries.\n\nKnown for his exceptional ability to translate complex AI concepts into actionable business strategies, Ashley brings hands-on experience from the frontlines of the AI revolution. He currently serves as Board President for the Association of Corporate Growth – Silicon Valley Chapter (ACGSV.org), where he advises startups, VCs, and PE firms on leveraging AI technologies in M&A activities.\n\nA successful entrepreneur himself, Ashley has founded and exited three startups. His unique combination of technical expertise (BS in Aerospace Engineering) and business acumen makes him a sought-after speaker at prestigious venues including Intel, Cisco, Cloudera, and IEEE National Conference.\n\nAshley's insights have been featured on The Silicon Valley Podcast and in prominent publications like Silicon Valley Business Times and San Francisco Business Times. His talks blend deep technical knowledge with practical business applications, helping organizations understand the \"art of the possible\" with AI technology.\n\nA former combat engineering officer in the US Army and current member of the 82nd Airborne Division Association, Ashley brings discipline and strategic thinking to every engagement. Based in San Francisco, he remains active in the startup ecosystem as a board advisor while pursuing interests in fly fishing, skiing, gaming, and cosplay.",
    programs: [
      "Practical adoption of AI use-cases",
      "Scaling impact Hi-Tech has on businesses",
      "Fast-Wins for AI with customers and businesses",
    ],
    fee: "Please Inquire",
    location: "San Francisco, California",
    linkedin: "https://www.linkedin.com/in/ashley-tarver/",
    email: "ashley@microsoft.com",
    contact: "Direct",
    listed: true,
    expertise: ["AI Implementation", "Enterprise Technology", "Business Strategy", "Technology Evangelism"],
    industries: ["Technology", "Enterprise", "Startups", "Consulting"],
    ranking: 78,
  },
  {
    slug: "vandi-verma",
    name: "Vandi Verma",
    title: "NASA JPL Robotics & AI Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Vandi Verma is a robotics and AI expert at NASA's Jet Propulsion Laboratory, where she works on autonomous systems for space exploration. She has been instrumental in developing AI systems for Mars rovers and other space missions.",
    programs: [
      "AI and Robotics in Space Exploration",
      "Autonomous Systems and Decision Making",
      "AI for Extreme Environments",
      "The Future of Space Technology",
    ],
    fee: "$40k-$60k",
    location: "Los Angeles, CA",
    email: "vandi@jpl.nasa.gov",
    contact: "NASA",
    listed: true,
    expertise: ["Space Robotics", "Autonomous Systems", "AI in Space", "Robotics Engineering"],
    industries: ["Aerospace", "Government", "Research", "Technology"],
    ranking: 75,
  },
  {
    slug: "joanna-bryson",
    name: "Prof. Joanna Bryson, PhD",
    title: "AI Ethics Researcher & Professor",
    image: "/speakers/joanna-bryson-headshot.jpg",
    bio: "Professor Joanna Bryson is a leading AI ethics researcher and professor at the Hertie School in Berlin. She has been at the forefront of AI governance and ethics discussions, advising governments and organizations on responsible AI development. Bryson's work focuses on the societal implications of AI and ensuring technology serves humanity.",
    programs: [
      "AI Ethics and Governance",
      "Responsible AI Development",
      "AI Policy and Regulation",
      "The Social Impact of Artificial Intelligence",
    ],
    fee: "Academic rates available",
    location: "Berlin, Germany",
    linkedin: "https://www.linkedin.com/in/bryson/",
    email: "Bryson@hertie-school.org",
    contact: "Peter",
    listed: true,
    expertise: ["AI Ethics", "AI Governance", "Technology Policy", "Academic Research"],
    industries: ["Academia", "Government", "Policy", "Research"],
    ranking: 20,
  },
  {
    slug: "maya-ackerman",
    name: "Maya Ackerman",
    title: "AI Creativity & Computational Creativity Expert",
    image: "/speakers/maya-ackerman-headshot.jpg",
    imagePosition: "top",
    bio: "Maya Ackerman is an AI creativity and computational creativity expert who explores how artificial intelligence can enhance and augment human creativity. She specializes in AI applications in creative industries and computational creativity research.",
    programs: [
      "AI and Computational Creativity",
      "The Future of Creative AI",
      "AI in Creative Industries",
      "Human-AI Creative Collaboration",
    ],
    fee: "$35k-$50k",
    location: "San Jose, CA",
    email: "maya@aicreative.com",
    contact: "Direct",
    listed: true,
    expertise: ["Computational Creativity", "AI Creativity", "Creative AI", "Human-AI Collaboration"],
    industries: ["Creative Industries", "Technology", "Entertainment", "Media"],
    ranking: 70,
  },
  {
    slug: "shafi-ahmed",
    name: "Shafi Ahmed",
    title: "Digital Health & AI in Surgery Expert",
    image: "/speakers/dr-shafi-ahmed-headshot.jpg",
    bio: "Shafi Ahmed is a pioneering surgeon and digital health expert who specializes in the application of AI and emerging technologies in healthcare and surgery. He is known for his work in virtual reality surgery and AI-assisted medical procedures.",
    programs: [
      "AI in Surgery and Healthcare",
      "Digital Health Innovation",
      "Virtual Reality in Medicine",
      "The Future of Medical Technology",
    ],
    fee: "$45k-$65k",
    location: "London, UK",
    email: "shafi@digitalsurgery.com",
    contact: "Direct",
    listed: true,
    expertise: ["AI in Healthcare", "Digital Surgery", "Medical Technology", "Virtual Reality"],
    industries: ["Healthcare", "Medical Devices", "Surgery", "Digital Health"],
    ranking: 24,
  },
  {
    slug: "harvey-castro",
    name: "Dr. Harvey Castro",
    title: "AI in Healthcare & Medical Innovation Expert",
    image: "/speakers/dr-harvey-castro-headshot.jpg",
    imagePosition: "top",
    bio: "Dr. Harvey Castro is a leading AI in healthcare expert and medical innovation specialist who focuses on the application of artificial intelligence in medical practice and healthcare delivery. He has extensive experience in medical AI implementation and healthcare technology innovation, helping organizations leverage AI to improve patient outcomes and healthcare efficiency.",
    programs: [
      "AI in Healthcare and Medical Practice",
      "Medical Innovation with AI",
      "Healthcare AI Implementation",
      "The Future of AI in Medicine",
    ],
    fee: "$40k-$60k",
    location: "Texas",
    email: "harvey@healthcareai.com",
    contact: "Direct",
    listed: true,
    expertise: ["Healthcare AI", "Medical Innovation", "Digital Health", "Medical Technology"],
    industries: ["Healthcare", "Medical Technology", "Digital Health", "Medicine"],
    ranking: 22,
  },
  {
    slug: "nancy-xu",
    name: "Nancy Xu",
    title: "AI Product Manager & Technology Leader",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Nancy Xu is an experienced AI product manager and technology leader who specializes in bringing AI products from concept to market. She has extensive experience in product development, user experience design, and AI implementation across various industries.",
    programs: [
      "AI Product Development and Strategy",
      "Building User-Centric AI Products",
      "AI Product Management Best Practices",
      "Technology Leadership in AI Companies",
    ],
    fee: "$30k-$45k",
    location: "Silicon Valley",
    email: "nancy@aiproducts.com",
    contact: "Direct",
    listed: true,
    expertise: ["AI Product Management", "Product Strategy", "User Experience", "Technology Leadership"],
    industries: ["Technology", "Software", "Startups", "Product Development"],
    ranking: 65,
  },
  {
    slug: "chris-yeh",
    name: "Chris Yeh",
    title: "AI Entrepreneur & Scaling Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Chris Yeh is an AI entrepreneur and scaling expert who helps companies grow and scale their AI initiatives. He is the co-author of 'Blitzscaling' and has extensive experience in building and scaling technology companies.",
    programs: [
      "Scaling AI Companies and Initiatives",
      "AI Entrepreneurship and Innovation",
      "Blitzscaling in the AI Era",
      "Building High-Growth AI Businesses",
    ],
    fee: "$40k-$60k",
    location: "Silicon Valley",
    email: "chris@blitzscaling.com",
    contact: "Direct",
    listed: true,
    expertise: ["AI Entrepreneurship", "Business Scaling", "Technology Strategy", "Innovation"],
    industries: ["Technology", "Startups", "Venture Capital", "Entrepreneurship"],
    ranking: 65,
  },
  {
    slug: "ben-parr",
    name: "Ben Parr",
    title: "AI Entrepreneur & Technology Journalist",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Ben Parr is an AI entrepreneur and technology journalist who has been covering the AI industry and building AI companies. He is the co-founder of Octane AI and has extensive experience in AI entrepreneurship and technology journalism.",
    programs: [
      "AI Entrepreneurship and Innovation",
      "Building AI Companies",
      "Technology Trends and AI",
      "AI in E-commerce and Marketing",
    ],
    fee: "35k-$50k",
    location: "San Francisco",
    email: "ben@octaneai.com",
    contact: "Direct",
    listed: true,
    expertise: ["AI Entrepreneurship", "Technology Journalism", "E-commerce AI", "AI Innovation"],
    industries: ["Technology", "E-commerce", "Media", "Startups"],
    ranking: 63,
  },
  {
    slug: "max-sills",
    name: "Max Sills",
    title: "AI Startup Advisor & Technology Investor",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Max Sills is an AI startup advisor and technology investor who helps early-stage companies navigate the AI landscape. He has extensive experience in AI venture capital and provides strategic guidance to AI startups and entrepreneurs.",
    programs: [
      "AI Startup Strategy and Funding",
      "Venture Capital in AI",
      "Building Successful AI Companies",
      "AI Investment Trends and Opportunities",
    ],
    fee: "$35k-$50k",
    location: "Silicon Valley",
    email: "max@aiventures.com",
    contact: "Direct",
    listed: true,
    expertise: ["AI Startups", "Venture Capital", "Technology Investment", "Entrepreneurship"],
    industries: ["Venture Capital", "Startups", "Technology", "Investment"],
    ranking: 60,
  },
  {
    slug: "christopher-ategeka",
    name: "Christopher Ategeka",
    title: "AI Innovation & Technology Leadership Expert",
    image: "/speakers/christopher-ategeka-headshot.jpg",
    imagePosition: "top",
    bio: "Christopher Ategeka is an AI innovation and technology leadership expert with extensive experience in building and scaling technology companies. He has been involved in various AI initiatives and helps organizations develop innovation strategies and implement cutting-edge AI solutions.",
    programs: [
      "AI Innovation and Leadership",
      "Technology Strategy and Development",
      "Building Innovation Culture",
      "AI Technology Implementation",
    ],
    fee: "$35k-$50k",
    location: "Silicon Valley",
    email: "christopher@aiinnovation.com",
    contact: "Direct",
    listed: true,
    expertise: ["AI Innovation", "Technology Leadership", "Innovation Strategy", "Technology Development"],
    industries: ["Technology", "Innovation", "Startups", "Leadership"],
    ranking: 25,
  },
  {
    slug: "ryan-pamplin",
    name: "Ryan Pamplin",
    title: "AI Marketing & Customer Experience Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Ryan Pamplin is an AI marketing and customer experience expert who helps companies leverage artificial intelligence to enhance customer relationships and drive business growth. He specializes in AI-powered marketing automation and personalization.",
    programs: [
      "AI-Powered Marketing and Personalization",
      "Customer Experience in the AI Era",
      "Marketing Automation and AI",
      "Data-Driven Customer Insights",
    ],
    fee: "$30k-$45k",
    location: "Chicago, IL",
    email: "ryan@aimarketing.com",
    contact: "Direct",
    listed: true,
    expertise: ["AI Marketing", "Customer Experience", "Marketing Automation", "Personalization"],
    industries: ["Marketing", "Retail", "E-commerce", "Technology"],
    ranking: 51,
  },
  {
    slug: "divya-chander",
    name: "Divya Chander",
    title: "Neuroscience & AI in Medicine Expert",
    image: "/speakers/divya-chander-headshot.png",
    bio: "Divya Chander is a neuroscience and AI in medicine expert who specializes in the application of artificial intelligence in neuroscience and medical practice. She has extensive experience in medical AI research and neurotechnology.",
    programs: [
      "AI in Neuroscience and Medicine",
      "Neurotechnology and AI",
      "Medical AI Research and Applications",
      "The Future of Neuroscience Technology",
    ],
    fee: "$40k-$60k",
    location: "Stanford, CA",
    email: "divya@neuroscienceai.com",
    contact: "Direct",
    listed: true,
    expertise: ["Neuroscience AI", "Medical AI", "Neurotechnology", "Medical Research"],
    industries: ["Healthcare", "Neuroscience", "Medical Research", "Technology"],
    ranking: 55,
  },
  {
    slug: "chris-duffey",
    name: "Chris Duffey",
    title: "AI Creative & Marketing Innovation Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Chris Duffey is an AI creative and marketing innovation expert who explores the intersection of artificial intelligence and creativity. He helps brands and organizations understand how AI can enhance creative processes and marketing effectiveness.",
    programs: [
      "AI and Creativity in Marketing",
      "The Future of Creative AI",
      "AI-Powered Brand Innovation",
      "Creative Technology and AI",
    ],
    fee: "$35k-$50k",
    location: "Los Angeles, CA",
    email: "chris@aicreative.com",
    contact: "Direct",
    listed: true,
    expertise: ["AI Creativity", "Marketing Innovation", "Creative Technology", "Brand Strategy"],
    industries: ["Marketing", "Advertising", "Creative Industries", "Technology"],
    ranking: 55,
  },
  {
    slug: "sounil-yu",
    name: "Sounil Yu",
    title: "Cybersecurity & AI Security Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Sounil Yu is a leading cybersecurity expert specializing in AI security and the intersection of artificial intelligence and cybersecurity. He helps organizations understand and mitigate security risks associated with AI systems and develop secure AI implementations.",
    programs: [
      "AI Security and Cybersecurity",
      "Securing AI Systems and Models",
      "AI-Powered Cyber Threats",
      "Building Secure AI Infrastructure",
    ],
    fee: "$40k-$55k",
    location: "New York",
    email: "sounil@aisecurity.com",
    contact: "Direct",
    listed: true,
    expertise: ["AI Security", "Cybersecurity", "Risk Management", "Security Architecture"],
    industries: ["Cybersecurity", "Technology", "Finance", "Government"],
    ranking: 52,
  },
  {
    slug: "oak-felder",
    name: "Oak Felder",
    title: "AI Music & Creative Technology Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Oak Felder is an AI music and creative technology expert who explores the intersection of artificial intelligence and music production. He has extensive experience in music technology and AI applications in creative industries.",
    programs: [
      "AI in Music Production and Creation",
      "Creative Technology and AI",
      "The Future of AI in Entertainment",
      "Music Technology Innovation",
    ],
    fee: "$30k-$45k",
    location: "Los Angeles, CA",
    email: "oak@aimusictech.com",
    contact: "Direct",
    listed: true,
    expertise: ["AI Music", "Creative Technology", "Music Production", "Entertainment AI"],
    industries: ["Music", "Entertainment", "Creative Industries", "Technology"],
    ranking: 53,
  },
  {
    slug: "david-ewing-duncan",
    name: "David Ewing Duncan",
    title: "Biotech & AI Futurist, Author",
    image: "/speakers/david-ewing-duncan-headshot.jpg",
    imagePosition: "top",
    bio: "David Ewing Duncan is a renowned author, journalist, and futurist specializing in biotechnology and artificial intelligence. He has written several bestselling books on the intersection of technology and human health, and is a frequent speaker on the future of medicine, longevity, and AI applications in healthcare.",
    programs: [
      "The Future of Human Longevity",
      "AI in Biotechnology and Medicine",
      "Genetic Engineering and Society",
      "Technology and Human Enhancement",
    ],
    fee: "$30k-$45k",
    location: "San Francisco",
    email: "speaking@davidduncan.com",
    contact: "Direct",
    listed: true,
    expertise: ["Biotechnology", "AI in Healthcare", "Longevity", "Genetic Engineering"],
    industries: ["Healthcare", "Biotechnology", "Pharmaceuticals", "Research"],
    ranking: 50,
  },
  {
    slug: "lital-marom",
    name: "Lital Marom",
    title: "AI Chatbots & Conversational AI Expert",
    image: "/speakers/lital-marom-headshot.jpeg",
    bio: "Lital Marom is an AI chatbots and conversational AI expert who specializes in developing intelligent conversational systems. She has extensive experience in chatbot development and conversational AI applications across various industries.",
    programs: [
      "Chatbots and Conversational AI",
      "Building Intelligent Conversational Systems",
      "AI Customer Service and Support",
      "The Future of Conversational Interfaces",
    ],
    fee: "$30k-$45k",
    location: "Tel Aviv, Israel",
    email: "lital@conversationalai.com",
    contact: "Direct",
    listed: true,
    expertise: ["Conversational AI", "Chatbots", "AI Customer Service", "Natural Language Processing"],
    industries: ["Technology", "Customer Service", "E-commerce", "Software"],
    ranking: 49,
  },
  {
    slug: "katie-mcmahon",
    name: "Katie McMahon",
    title: "AI Strategy & Innovation Expert",
    image: "/speakers/Katie-McMahon-Headshot.jpeg",
    bio: "Katie McMahon is a leading AI strategy and innovation expert who helps organizations navigate the complexities of artificial intelligence implementation. With extensive experience in technology consulting and AI transformation, she specializes in helping companies develop comprehensive AI strategies that drive business value.",
    programs: [
      "AI Strategy for Business Leaders",
      "Innovation Management in the AI Era",
      "Digital Transformation and AI",
      "Building AI-Ready Organizations",
    ],
    fee: "$30k-$45k",
    location: "New York",
    email: "katie@aimcmahon.com",
    contact: "Direct",
    listed: true,
    expertise: ["AI Strategy", "Innovation Management", "Digital Transformation", "Business AI"],
    industries: ["Technology", "Consulting", "Finance", "Healthcare"],
    ranking: 48,
  },
  {
    slug: "dan-russell",
    name: "Dan Russell",
    title: "Google Search & AI Research Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Dan Russell is a Google search and AI research expert who has been instrumental in developing search technologies and AI applications. He specializes in information retrieval, search algorithms, and AI-powered information systems.",
    programs: [
      "Search Technology and AI",
      "Information Retrieval Systems",
      "AI-Powered Search and Discovery",
      "The Future of Information Access",
    ],
    fee: "$35k-$50k",
    location: "Mountain View, CA",
    email: "dan@googlesearch.com",
    contact: "Google",
    listed: true,
    expertise: ["Search Technology", "Information Retrieval", "AI Research", "Google Technologies"],
    industries: ["Technology", "Search", "Information Systems", "AI"],
    ranking: 45,
  },
  {
    slug: "vicki-reyzelman",
    name: "Vicki Reyzelman",
    title: "AI Healthcare & Medical Technology Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Vicki Reyzelman is an AI healthcare and medical technology expert who specializes in the application of artificial intelligence in healthcare settings. She has extensive experience in medical AI implementation and healthcare technology innovation.",
    programs: [
      "AI in Healthcare and Medicine",
      "Medical Technology Innovation",
      "Healthcare AI Implementation",
      "Digital Health Transformation",
    ],
    fee: "$35k-$50k",
    location: "San Francisco",
    email: "vicki@healthcareai.com",
    contact: "Direct",
    listed: true,
    expertise: ["Healthcare AI", "Medical Technology", "Digital Health", "Healthcare Innovation"],
    industries: ["Healthcare", "Medical Technology", "Digital Health", "Pharmaceuticals"],
    ranking: 45,
  },
  {
    slug: "zach-rattner",
    name: "Zach Rattner",
    title: "AI Gaming & Interactive Technology Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Zach Rattner is an AI gaming and interactive technology expert who specializes in the application of artificial intelligence in gaming and interactive entertainment. He has extensive experience in game AI and interactive technology development.",
    programs: [
      "AI in Gaming and Interactive Entertainment",
      "Game AI Development",
      "Interactive Technology Innovation",
      "The Future of AI in Gaming",
    ],
    fee: "$35k-$50k",
    location: "San Francisco",
    email: "zach@gamingai.com",
    contact: "Direct",
    listed: true,
    expertise: ["Gaming AI", "Interactive Technology", "Game Development", "Entertainment Technology"],
    industries: ["Gaming", "Entertainment", "Technology", "Interactive Media"],
    ranking: 50,
  },
  {
    slug: "robin-farmanfarmaian",
    name: "Robin Farmanfarmaian",
    title: "Digital Health & AI Innovation Expert",
    image: "/speakers/robin-farmanfarmaian-headshot.jpg",
    bio: "Robin Farmanfarmaian is a digital health and AI innovation expert who helps healthcare organizations leverage emerging technologies. She is an author, speaker, and consultant specializing in healthcare technology and AI applications in medicine.",
    programs: [
      "Digital Health Innovation and AI",
      "Healthcare Technology Transformation",
      "AI Applications in Patient Care",
      "The Future of Healthcare Technology",
    ],
    fee: "$35k-$50k",
    location: "Silicon Valley",
    email: "robin@digitalhealthai.com",
    contact: "Direct",
    listed: true,
    expertise: ["Digital Health", "Healthcare AI", "Medical Innovation", "Healthcare Technology"],
    industries: ["Healthcare", "Digital Health", "Medical Devices", "Technology"],
    ranking: 43,
  },
  {
    slug: "roman-yampolskiy",
    name: "Roman Yampolskiy",
    title: "AI Safety & Security Researcher",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Roman Yampolskiy is a leading AI safety and security researcher who focuses on the risks and challenges associated with artificial intelligence. He is a professor and researcher specializing in AI safety, security, and the long-term implications of AI development.",
    programs: [
      "AI Safety and Security Challenges",
      "The Risks of Artificial Intelligence",
      "AI Alignment and Control Problems",
      "Long-term AI Safety Research",
    ],
    fee: "$30k-$45k",
    location: "Louisville, KY",
    email: "roman@aisafety.edu",
    contact: "University",
    listed: true,
    expertise: ["AI Safety", "AI Security", "AI Risk Assessment", "AI Research"],
    industries: ["Academia", "Research", "Government", "Technology"],
    ranking: 39,
  },
  {
    slug: "sonal-gupta",
    name: "Sonal Gupta",
    title: "AI Research Scientist & NLP Expert",
    image: "/speakers/sonal-gupta-headshot.jpg",
    bio: "Sonal Gupta is a leading AI research scientist specializing in natural language processing and conversational AI. With extensive experience in developing AI systems that understand and generate human language, she has contributed to breakthrough advances in NLP and machine learning applications.",
    programs: [
      "Natural Language Processing and AI",
      "Conversational AI Systems",
      "Machine Learning Research",
      "The Future of Human-AI Communication",
    ],
    fee: "$35k-$50k",
    location: "Silicon Valley",
    email: "sonal@nlpresearch.com",
    contact: "Direct",
    listed: true,
    expertise: ["Natural Language Processing", "Conversational AI", "Machine Learning", "AI Research"],
    industries: ["Technology", "Research", "Software", "AI"],
    ranking: 20,
  },
  {
    slug: "brad-templeton",
    name: "Brad Templeton",
    title: "Autonomous Vehicles & AI Transportation Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Brad Templeton is an autonomous vehicles and AI transportation expert who has been at the forefront of self-driving car technology. He has extensive experience in transportation AI and helps organizations understand the future of mobility and autonomous systems.",
    programs: [
      "Autonomous Vehicles and Self-Driving Cars",
      "AI in Transportation and Mobility",
      "The Future of Transportation Technology",
      "Smart Cities and Autonomous Systems",
    ],
    fee: "$35k-$50k",
    location: "Silicon Valley",
    email: "brad@autonomousvehicles.com",
    contact: "Direct",
    listed: true,
    expertise: ["Autonomous Vehicles", "Transportation AI", "Self-Driving Technology", "Mobility Innovation"],
    industries: ["Automotive", "Transportation", "Technology", "Smart Cities"],
    ranking: 37,
  },
  {
    slug: "alex-salkever",
    name: "Alex Salkever",
    title: "Technology Author & AI Business Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Alex Salkever is a technology author and business expert specializing in artificial intelligence and digital transformation. He has written extensively about the business implications of AI and helps organizations understand how to leverage emerging technologies for competitive advantage.",
    programs: [
      "AI Business Strategy and Implementation",
      "Digital Transformation Leadership",
      "Technology Trends and Business Impact",
      "The Future of Work in the AI Era",
    ],
    fee: "$30k-$45k",
    location: "San Francisco",
    email: "alex@salkever.com",
    contact: "Direct",
    listed: true,
    expertise: ["AI Business Strategy", "Digital Transformation", "Technology Writing", "Business Innovation"],
    industries: ["Technology", "Media", "Consulting", "Publishing"],
    ranking: 40,
  },
  {
    slug: "stefano-bini",
    name: "Stefano Bini",
    title: "AI Healthcare & Medical Innovation Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Stefano Bini is an AI healthcare and medical innovation expert who specializes in the application of artificial intelligence in medical practice and healthcare delivery. He has extensive experience in medical AI implementation and healthcare technology innovation.",
    programs: [
      "AI in Medical Practice and Healthcare",
      "Medical Innovation and Technology",
      "Healthcare AI Implementation",
      "Digital Medicine and AI",
    ],
    fee: "$35k-$50k",
    location: "San Francisco",
    email: "stefano@medicalai.com",
    contact: "Direct",
    listed: true,
    expertise: ["Medical AI", "Healthcare Innovation", "Digital Medicine", "Medical Technology"],
    industries: ["Healthcare", "Medical Technology", "Digital Health", "Medicine"],
    ranking: 33,
  },
  {
    slug: "rafael-grossmann",
    name: "Rafael Grossmann",
    title: "Digital Surgery & AI in Medicine Expert",
    image: "/speakers/rafael-grossmann-headshot.jpg",
    imagePosition: "top",
    bio: "Rafael Grossmann is a digital surgery and AI in medicine expert who pioneered the use of emerging technologies in surgical practice. He is known for his innovative work in digital health and AI applications in surgery and medical education.",
    programs: [
      "Digital Surgery and AI in Medicine",
      "Innovation in Medical Technology",
      "AI Applications in Surgery",
      "The Future of Medical Practice",
    ],
    fee: "$40k-$60k",
    location: "Vermont",
    email: "rafael@digitalsurgery.com",
    contact: "Direct",
    listed: true,
    expertise: ["Digital Surgery", "Medical AI", "Surgical Innovation", "Medical Technology"],
    industries: ["Healthcare", "Surgery", "Medical Technology", "Digital Health"],
    ranking: 31,
  },
  {
    slug: "sagar-savla",
    name: "Sagar Savla",
    title: "AI Engineering & Machine Learning Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Sagar Savla is an AI engineering and machine learning expert with extensive experience in building and deploying AI systems at scale. He specializes in machine learning infrastructure, AI model optimization, and enterprise AI implementation.",
    programs: [
      "AI Engineering and Infrastructure",
      "Machine Learning at Scale",
      "AI Model Optimization and Deployment",
      "Enterprise AI Implementation",
    ],
    fee: "$35k-$50k",
    location: "San Francisco",
    email: "sagar@aiengineering.com",
    contact: "Direct",
    listed: true,
    expertise: ["AI Engineering", "Machine Learning", "AI Infrastructure", "Model Deployment"],
    industries: ["Technology", "Software", "Cloud Computing", "Enterprise"],
    ranking: 30,
  },
  {
    slug: "simone-bianco",
    name: "Simone Bianco",
    title: "AI Research Scientist & Computer Vision Expert",
    image: "/speakers/simone-bianco-headshot.jpg",
    bio: "Simone Bianco is an AI research scientist specializing in computer vision and machine learning. He has made significant contributions to the field of visual AI and has extensive experience in developing computer vision systems for various applications.",
    programs: [
      "Computer Vision and Visual AI",
      "Machine Learning Research",
      "AI Applications in Visual Recognition",
      "Deep Learning for Computer Vision",
    ],
    fee: "$35k-$50k",
    location: "Milan, Italy",
    email: "simone@visionai.com",
    contact: "Direct",
    listed: true,
    expertise: ["Computer Vision", "Machine Learning", "Visual AI", "Deep Learning"],
    industries: ["Technology", "Research", "Automotive", "Healthcare"],
    ranking: 28,
  },
  {
    slug: "larry-magid",
    name: "Larry Magid",
    title: "Technology Journalist & AI Ethics Expert",
    image: "/speakers/larry-magid-headshot.jpeg",
    bio: "Larry Magid is a technology journalist and AI ethics expert who has been covering technology trends and their societal implications for decades. He specializes in technology policy, digital safety, and the ethical implications of AI development.",
    programs: [
      "AI Ethics and Digital Safety",
      "Technology Policy and Regulation",
      "The Social Impact of AI",
      "Digital Citizenship in the AI Era",
    ],
    fee: "$25k-$40k",
    location: "Silicon Valley",
    email: "larry@techpolicy.com",
    contact: "Direct",
    listed: true,
    expertise: ["Technology Journalism", "AI Ethics", "Digital Safety", "Technology Policy"],
    industries: ["Media", "Technology", "Policy", "Education"],
    ranking: 27,
  },
  {
    slug: "mike-cassidy",
    name: "Mike Cassidy",
    title: "AI Innovation & Technology Leadership Expert",
    image: "/speakers/mike-cassidy-headshot.png",
    bio: "Mike Cassidy is an AI innovation and technology leadership expert with extensive experience in building and leading technology companies. He has been involved in various AI initiatives and helps organizations develop innovation strategies.",
    programs: [
      "AI Innovation and Leadership",
      "Technology Strategy and Development",
      "Building Innovation Culture",
      "AI Technology Implementation",
    ],
    fee: "$35k-$50k",
    location: "Silicon Valley",
    email: "mike@aiinnovation.com",
    contact: "Direct",
    listed: true,
    expertise: ["AI Innovation", "Technology Leadership", "Innovation Strategy", "Technology Development"],
    industries: ["Technology", "Innovation", "Startups", "Leadership"],
    ranking: 25,
  },
  {
    slug: "alfred-poor",
    name: "Alfred Poor",
    title: "Health Technology & AI Wearables Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Alfred Poor is a health technology and AI wearables expert who specializes in the intersection of artificial intelligence and health monitoring devices. He has extensive experience in health tech innovation and AI applications in wearable technology.",
    programs: [
      "AI in Health Technology and Wearables",
      "Health Monitoring and AI",
      "Wearable Technology Innovation",
      "The Future of Health Tech",
    ],
    fee: "$30k-$45k",
    location: "Pennsylvania",
    email: "alfred@healthtechai.com",
    contact: "Direct",
    listed: true,
    expertise: ["Health Technology", "Wearable AI", "Health Monitoring", "Medical Devices"],
    industries: ["Healthcare", "Wearable Technology", "Medical Devices", "Health Tech"],
    ranking: 3,
  },
  {
    slug: "peter-small",
    name: "Peter Small",
    title: "AI Business Strategy & Technology Consulting Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Peter Small is an AI business strategy and technology consulting expert who helps organizations develop and implement AI strategies. He has extensive experience in technology consulting and AI business transformation.",
    programs: [
      "AI Business Strategy and Implementation",
      "Technology Consulting and AI",
      "Digital Transformation with AI",
      "AI Strategy for Business Leaders",
    ],
    fee: "$30k-$45k",
    location: "New York",
    email: "peter@aibusinessstrategy.com",
    contact: "Direct",
    listed: true,
    expertise: ["AI Business Strategy", "Technology Consulting", "Digital Transformation", "Business AI"],
    industries: ["Consulting", "Technology", "Business Strategy", "AI"],
    ranking: 21,
  },
  {
    slug: "simon-pierro",
    name: "Simon Pierro",
    title: "Digital Magic & AI Entertainment Expert",
    image: "/speakers/simon-pierro-youtube.jpg",
    bio: "Simon Pierro is a digital magician and AI entertainment expert who combines magic with cutting-edge technology. He demonstrates the possibilities of AI and emerging technologies through innovative performances and presentations.",
    programs: [
      "AI and the Future of Entertainment",
      "Digital Magic and Technology",
      "Innovation Through Creative Technology",
      "Engaging Audiences with AI Demonstrations",
    ],
    fee: "$25k-$40k",
    location: "Germany/Global",
    email: "simon@digitalmagic.com",
    contact: "Direct",
    listed: true,
    expertise: ["Digital Entertainment", "AI Demonstrations", "Technology Innovation", "Creative Technology"],
    industries: ["Entertainment", "Technology", "Events", "Creative Industries"],
    ranking: 20,
  },
  {
    slug: "matthew-blakemore",
    name: "Matthew Blakemore",
    title: "AI Technology & Innovation Consultant",
    image: "/speakers/matthew-blakemore-headshot.jpg",
    imagePosition: "top",
    bio: "Matthew Blakemore is an AI technology and innovation consultant who helps organizations navigate the AI landscape and implement innovative AI solutions. He has extensive experience in technology innovation and AI consulting.",
    programs: [
      "AI Technology Innovation",
      "AI Implementation Strategies",
      "Technology Innovation Consulting",
      "AI Transformation for Organizations",
    ],
    fee: "$30k-$45k",
    location: "London, UK",
    email: "matthew@aitechconsulting.com",
    contact: "Direct",
    listed: true,
    expertise: ["AI Technology", "Innovation Consulting", "Technology Strategy", "AI Implementation"],
    industries: ["Technology", "Consulting", "Innovation", "AI"],
    ranking: 19,
  },
  {
    slug: "chris-jones",
    name: "Chris Jones",
    title: "AI Technology & Innovation Consultant",
    image: "/speakers/chris-jones-headshot.jpg",
    bio: "Chris Jones is an AI technology and innovation consultant who helps organizations implement artificial intelligence solutions and develop innovation strategies. He has extensive experience in technology consulting and AI transformation across various industries.",
    programs: [
      "AI Implementation and Strategy",
      "Technology Innovation Consulting",
      "Digital Transformation with AI",
      "Building AI-Driven Organizations",
    ],
    fee: "$30k-$45k",
    location: "Austin, TX",
    email: "chris@aitechconsulting.com",
    contact: "Direct",
    listed: true,
    expertise: ["AI Consulting", "Technology Innovation", "Digital Transformation", "Strategy Development"],
    industries: ["Technology", "Consulting", "Manufacturing", "Finance"],
    ranking: 10,
  },
  {
    slug: "shawn-flynn",
    name: "Shawn Flynn",
    title: "AI Investment & Silicon Valley Expert",
    image: "/speakers/shawn-flynn-headshot.jpg",
    bio: "Shawn Flynn is an AI investment expert and Silicon Valley insider who provides insights into AI investment trends and startup ecosystems. He helps investors and entrepreneurs navigate the AI landscape and identify promising opportunities.",
    programs: [
      "AI Investment Trends and Opportunities",
      "Silicon Valley AI Ecosystem",
      "AI Startup Evaluation and Strategy",
      "Technology Investment Analysis",
    ],
    fee: "$35k-$50k",
    location: "Silicon Valley",
    email: "shawn@aiinvestments.com",
    contact: "Direct",
    listed: true,
    expertise: ["AI Investment", "Venture Capital", "Startup Ecosystem", "Technology Analysis"],
    industries: ["Venture Capital", "Investment", "Technology", "Startups"],
    ranking: 15,
  },
  {
    slug: "david-fajgenbaum",
    name: "David Fajgenbaum",
    title: "AI in Drug Discovery & Medical Research Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "David Fajgenbaum is an AI in drug discovery and medical research expert who specializes in using artificial intelligence to accelerate medical research and drug development. He has extensive experience in medical AI research and pharmaceutical innovation.",
    programs: [
      "AI in Drug Discovery and Development",
      "Medical Research and AI",
      "Pharmaceutical Innovation with AI",
      "Accelerating Medical Breakthroughs with AI",
    ],
    fee: "$40k-$60k",
    location: "Philadelphia, PA",
    email: "david@drugdiscoveryai.com",
    contact: "Direct",
    listed: true,
    expertise: ["Drug Discovery AI", "Medical Research", "Pharmaceutical AI", "Medical Innovation"],
    industries: ["Pharmaceuticals", "Medical Research", "Healthcare", "Biotechnology"],
    ranking: 11,
  },
  {
    slug: "dan-lohrmann",
    name: "Dan Lohrmann",
    title: "Cybersecurity & AI Security Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Dan Lohrmann is a leading cybersecurity expert specializing in AI security and government technology. He has extensive experience in cybersecurity strategy and helps organizations understand the security implications of AI adoption.",
    programs: [
      "AI Security and Cybersecurity Strategy",
      "Government Technology and AI",
      "Cybersecurity Risk Management",
      "Securing AI Systems and Infrastructure",
    ],
    fee: "$35k-$50k",
    location: "Michigan",
    email: "dan@cybersecurityai.com",
    contact: "Direct",
    listed: true,
    expertise: ["Cybersecurity", "AI Security", "Government Technology", "Risk Management"],
    industries: ["Government", "Cybersecurity", "Technology", "Public Sector"],
    ranking: 10,
  },
  {
    slug: "tatyana-mamut",
    name: "Tatyana Mamut",
    title: "AI Product Strategy & Technology Leadership Expert",
    image: "/speakers/tatyana-mamut-expanded-headshot.png",
    bio: "Tatyana Mamut is an AI product strategy and technology leadership expert with extensive experience in building and scaling AI products. She has held senior leadership positions at major technology companies and specializes in AI product development and strategy.",
    programs: [
      "AI Product Strategy and Development",
      "Technology Leadership in AI",
      "Building Scalable AI Products",
      "AI Product Management Excellence",
    ],
    fee: "$40k-$60k",
    location: "San Francisco",
    email: "tatyana@aiproductstrategy.com",
    contact: "Direct",
    listed: true,
    expertise: ["AI Product Strategy", "Technology Leadership", "Product Development", "AI Innovation"],
    industries: ["Technology", "Software", "Product Management", "AI"],
    ranking: 8,
  },
  {
    slug: "rene-caissie",
    name: "Rene Caissie",
    title: "AI Accessibility & Inclusive Technology Expert",
    image: "/speakers/rene-caissie-headshot.jpg",
    imagePosition: "top",
    bio: "Rene Caissie is an AI accessibility and inclusive technology expert who specializes in making artificial intelligence accessible to people with disabilities. He has extensive experience in accessibility technology and inclusive AI design.",
    programs: [
      "AI Accessibility and Inclusive Design",
      "Technology for People with Disabilities",
      "Inclusive AI Development",
      "Accessibility in the AI Era",
    ],
    fee: "$30k-$45k",
    location: "Canada",
    email: "rene@accessibleai.com",
    contact: "Direct",
    listed: true,
    expertise: ["AI Accessibility", "Inclusive Technology", "Disability Technology", "Accessible Design"],
    industries: ["Technology", "Accessibility", "Non-profit", "Education"],
    ranking: 7,
  },
  {
    slug: "paolo-privitera",
    name: "Paolo Privitera",
    title: "AI Research & Innovation Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Paolo Privitera is an AI research and innovation expert who specializes in applied AI research and technology innovation. He has extensive experience in developing AI solutions for various industries and applications.",
    programs: [
      "Applied AI Research and Development",
      "AI Innovation Strategies",
      "Technology Research and Development",
      "AI Applications Across Industries",
    ],
    fee: "$35k-$50k",
    location: "Europe",
    email: "paolo@airesearch.com",
    contact: "Direct",
    listed: true,
    expertise: ["AI Research", "Technology Innovation", "Applied AI", "Research Development"],
    industries: ["Research", "Technology", "Innovation", "Academia"],
    ranking: 4,
  },
  {
    slug: "lee-sanders",
    name: "Lee Sanders",
    title: "AI Business Intelligence & Data Analytics Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Lee Sanders is an AI business intelligence and data analytics expert who specializes in using artificial intelligence to enhance business decision-making. He has extensive experience in AI-powered analytics and business intelligence systems.",
    programs: [
      "AI-Powered Business Intelligence",
      "Data Analytics and AI",
      "Business Decision Making with AI",
      "AI in Business Operations",
    ],
    fee: "$30k-$45k",
    location: "Chicago, IL",
    email: "lee@aibusinessintelligence.com",
    contact: "Direct",
    listed: true,
    expertise: ["Business Intelligence", "Data Analytics", "AI Analytics", "Business AI"],
    industries: ["Business Intelligence", "Analytics", "Technology", "Consulting"],
    ranking: 2,
  },
  {
    slug: "lucien-engelen",
    name: "Lucien Engelen",
    title: "Digital Health Innovation & AI in Healthcare Expert",
    image: "/speakers/lucien-engelen-headshot.jpg",
    bio: "Lucien Engelen is a digital health innovation expert and AI in healthcare specialist who focuses on transforming healthcare through emerging technologies. He has extensive experience in healthcare innovation and helps organizations implement AI solutions to improve patient outcomes and healthcare delivery.",
    programs: [
      "Digital Health Innovation and AI",
      "Healthcare Technology Transformation",
      "AI Applications in Patient Care",
      "The Future of Healthcare Technology",
    ],
    fee: "$40k-$60k",
    location: "Netherlands",
    email: "lucien@healthcareinnovation.com",
    contact: "Direct",
    listed: true,
    expertise: ["Digital Health", "Healthcare AI", "Medical Innovation", "Healthcare Technology"],
    industries: ["Healthcare", "Digital Health", "Medical Technology", "Innovation"],
    ranking: 93,
  },
  {
    slug: "vishal-sharma",
    name: "Vishal Sharma",
    title: "VP of AGI at Amazon",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Vishal Sharma is the Vice President of Artificial General Intelligence (AGI) at Amazon, where he leads cutting-edge research and development in advanced AI systems. With extensive experience in machine learning, deep learning, and AI research, Vishal is at the forefront of developing next-generation AI technologies that push the boundaries of what's possible with artificial intelligence.\n\nIn his role at Amazon, Vishal oversees strategic initiatives in AGI development, working on breakthrough technologies that aim to create more general and adaptable AI systems. His work spans multiple domains including natural language processing, computer vision, robotics, and autonomous systems, with a focus on developing AI that can understand, learn, and adapt across diverse tasks and environments.\n\nVishal brings a unique perspective to AI development, combining deep technical expertise with strategic business acumen. His leadership in AGI research positions him as one of the key figures shaping the future of artificial intelligence and its applications across industries.",
    programs: [
      "The Future of Artificial General Intelligence",
      "AGI Development at Scale",
      "Building Next-Generation AI Systems",
      "AI Research and Innovation Strategy",
    ],
    fee: "Please Inquire",
    location: "Seattle, Washington",
    email: "vishal@amazon.com",
    contact: "Amazon",
    listed: true,
    expertise: ["Artificial General Intelligence", "Machine Learning", "AI Research", "Deep Learning"],
    industries: ["Technology", "AI Research", "Cloud Computing", "Enterprise"],
    ranking: 95,
  },
  {
    slug: "gary-bolles",
    name: "Gary Bolles",
    title: "Chair for the Future of Work at Singularity University, Author, and Future of Work Expert",
    image: "/speakers/Bolles_Gary_speaking.jpeg",
    bio: "Gary Bolles is a leading expert on the future of work and the Chair for the Future of Work at Singularity University. He is a renowned speaker, author, and consultant who helps organizations navigate the rapidly changing landscape of work in the age of artificial intelligence and automation.\n\nAs the author of 'The Next Rules of Work: The Mindset, Skillset and Toolset to Lead Your Organization Through Uncertainty,' Gary provides practical insights into how individuals and organizations can thrive in an era of technological disruption. His work focuses on the intersection of technology, human potential, and organizational transformation.\n\nGary has advised Fortune 500 companies, government agencies, and educational institutions on workforce development, digital transformation, and the strategic implications of emerging technologies. His expertise spans across areas including AI's impact on employment, reskilling and upskilling strategies, and building resilient organizations for the future.\n\nWith over two decades of experience in technology and business strategy, Gary brings a unique perspective to understanding how artificial intelligence and automation will reshape the nature of work. He is a frequent keynote speaker at major conferences and has been featured in leading publications for his insights on the future of work.",
    programs: [
      "The Future of Work in the Age of AI",
      "Building Resilient Organizations for Tomorrow",
      "Reskilling and Upskilling for the AI Era",
      "Leading Through Technological Disruption",
    ],
    fee: "$35k-$50k",
    location: "San Francisco, California",
    email: "gary@futureofwork.com",
    contact: "Direct",
    listed: true,
    expertise: ["Future of Work", "AI Impact on Employment", "Workforce Development", "Organizational Transformation"],
    industries: ["Technology", "Human Resources", "Education", "Consulting"],
    ranking: 76,
  },
  {
    slug: "jamie-metzl",
    name: "Jamie Metzl",
    title: "Technology Futurist, Geopolitics Expert, and Author",
    image: "/speakers/jamie-metzl-headshot.jpeg",
    bio: "Jamie Metzl is a technology futurist, geopolitical expert, and author specializing in the intersection of artificial intelligence, genetics, and international relations. He is a leading voice on the ethical and societal implications of emerging technologies.",
    programs: [
      "AI, Genetics, and the Future of Humanity",
      "Geopolitics in the Age of AI",
      "The Ethical Implications of Emerging Technologies",
      "Human Enhancement and Society",
    ],
    fee: "$40k-$60k",
    location: "New York City, New York",
    linkedin: "https://www.linkedin.com/in/jamiemetzl/",
    website: "https://jamiemetzl.com/",
    email: "jamie@jamiemetzl.com",
    contact: "Direct",
    listed: true,
    expertise: ["AI Ethics", "Biotechnology", "Geopolitics", "Future of Technology"],
    industries: ["Technology", "Healthcare", "Government", "Consulting"],
    ranking: 72,
  },
  {
    slug: "andrew-mayne",
    name: "Andrew Mayne",
    title: "AI & Creativity Expert, Magician, and Author",
    image: "/speakers/andrew-mayne-headshot.jpeg",
    bio: "Andrew Mayne is an AI and creativity expert, renowned magician, and bestselling author. He explores the intersection of artificial intelligence and human creativity, demonstrating how AI can augment and inspire innovative thinking.",
    programs: [
      "AI and Human Creativity",
      "Innovation Through AI",
      "The Art of AI-Powered Problem Solving",
      "Future of Creative Industries with AI",
    ],
    fee: "$30k-$45k",
    location: "Los Angeles, CA",
    linkedin: "https://www.linkedin.com/in/andrewmayne/",
    website: "https://andrewmayne.com/",
    email: "andrew@andrewmayne.com",
    contact: "Direct",
    listed: true,
    expertise: ["AI Creativity", "Innovation", "Creative Thinking", "Technology & Art"],
    industries: ["Entertainment", "Technology", "Creative Industries", "Consulting"],
    ranking: 68,
  },
]

let _cachedSpeakers: Speaker[] | null = null

async function loadSpeakers(): Promise<Speaker[]> {
  if (_cachedSpeakers) {
    return _cachedSpeakers
  }

  const sheetSpeakers = await fetchSpeakersFromSheet()
  if (sheetSpeakers.length > 0) {
    _cachedSpeakers = sheetSpeakers
    return sheetSpeakers
  }

  // Fallback to local data if sheet fetch fails or returns no data
  console.warn("Failed to load speakers from Google Sheet. Falling back to local data.")
  _cachedSpeakers = localSpeakers.sort((a, b) => b.ranking - a.ranking)
  return _cachedSpeakers
}

export async function getAllSpeakers(): Promise<Speaker[]> {
  const speakers = await loadSpeakers()
  return speakers.filter((speaker) => speaker.listed)
}

export async function getSpeakerBySlug(slug: string): Promise<Speaker | undefined> {
  const speakers = await loadSpeakers()
  return speakers.find((speaker) => speaker.slug === slug)
}

export async function searchSpeakers(query: string): Promise<Speaker[]> {
  const speakers = await loadSpeakers()
  const lowercaseQuery = query.toLowerCase().trim()

  if (!lowercaseQuery) {
    return speakers.filter((speaker) => speaker.listed)
  }

  return speakers.filter((speaker) => {
    if (!speaker.listed) return false

    const nameWords = speaker.name.toLowerCase().split(/\s+/)
    const titleWords = speaker.title.toLowerCase().split(/\s+/)

    const nameMatch = nameWords.some((word) => word.includes(lowercaseQuery))
    const titleMatch = titleWords.some((word) => word.includes(lowercaseQuery))

    const expertiseMatch = speaker.expertise.some((skill) => skill.toLowerCase().includes(lowercaseQuery))
    const industryMatch = speaker.industries.some((industry) => industry.toLowerCase().includes(lowercaseQuery))

    const bioMatch = lowercaseQuery.length >= 4 && speaker.bio.toLowerCase().includes(lowercaseQuery)

    return nameMatch || titleMatch || expertiseMatch || industryMatch || bioMatch
  })
}

export async function getSpeakersByIndustry(industry: string): Promise<Speaker[]> {
  const speakers = await loadSpeakers()
  return speakers.filter(
    (speaker) => speaker.listed && speaker.industries.some((ind) => ind.toLowerCase().includes(industry.toLowerCase())),
  )
}

export async function getFeaturedSpeakers(count = 8): Promise<Speaker[]> {
  const speakers = await getAllSpeakers()
  return speakers.slice(0, count)
}

export async function getTopSpeakers(count = 6): Promise<Speaker[]> {
  const speakers = await getAllSpeakers()
  return speakers.slice(0, count)
}
