export interface Speaker {
  slug: string
  name: string
  title: string
  image: string
  bio: string
  programs: string[]
  fee: string
  location: string
  linkedin?: string
  website?: string
  email: string
  contact: string
  listed: boolean
  expertise: string[]
  industries: string[]
  ranking: number // New ranking field (1-100, higher = more prominent)
}

export const speakers: Speaker[] = [
  {
    slug: "adam-cheyer",
    name: "Adam Cheyer",
    title: "Co-Founder of Siri",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Adam Cheyer is a computer scientist and entrepreneur who co-founded Siri (acquired by Apple for over $200 million) and Viv Labs (acquired by Samsung). He is a pioneer in conversational AI and virtual assistant technology, with over 60 patents in AI and interface design. Cheyer has been at the forefront of making AI accessible to everyday users through natural language interfaces.",
    programs: [
      "The Evolution of Conversational AI",
      "Building Virtual Assistants That Actually Work",
      "Voice Technology and the Future of Human-Computer Interaction",
      "AI Product Development: From Research to Market",
    ],
    fee: "$50-$60k",
    location: "Oakland International Airport",
    linkedin: "https://www.linkedin.com/in/adamcheyer/",
    website: "http://adam.cheyer.com/site/home",
    email: "adam.cheyer@gmail.com",
    contact: "Direct",
    listed: true,
    expertise: ["Conversational AI", "Virtual Assistants", "Voice Technology", "AI Product Development"],
    industries: ["Technology", "Consumer Electronics", "Mobile"],
    ranking: 99,
  },
  {
    slug: "peter-norvig",
    name: "Peter Norvig",
    title: "Former Head of Computational Science at NASA and Director of Research and Search Quality at Google",
    image: "/speakers/peter-norvig-headshot.jpg",
    bio: 'Peter Norvig, a distinguished American computer scientist, is widely recognized for his profound contributions to artificial intelligence and education. As a Distinguished Education Fellow at the Stanford Institute for Human-Centered AI and a former director at Google, Norvig has been instrumental in shaping the field of AI. His co-authorship of "Artificial Intelligence: A Modern Approach," the most widely used textbook in AI, used in over 1,500 universities worldwide, highlights his academic influence.\n\nNorvig\'s career spans various pivotal roles, including leading the Computational Sciences Division at NASA Ames Research Center and contributing to advancements at companies like Junglee and Sun Microsystems Laboratories. His academic tenure includes positions at the University of Southern California and Berkeley, enhancing his reputation as a scholar and educator. His publications in AI, natural language processing, and information retrieval, notably "Paradigms of AI Programming" and "Intelligent Help Systems for UNIX," have been seminal in the field.\n\nA pioneer in online education, Norvig\'s collaboration with Sebastian Thrun to develop an online AI course attracted over 160,000 students, demonstrating his commitment to accessible, high-quality education. His influential publications, like the "Teach Yourself Programming in Ten Years" article and "The Unreasonable Effectiveness of Data," have significantly impacted how we understand programming and data\'s role in AI.\n\nAs a sought-after speaker, Norvig has shared his expertise globally, including notable presentations for the University of British Columbia and in his TED Talk. His work has not only advanced the technical aspects of AI but also its educational and ethical dimensions. Peter Norvig remains a pivotal figure in AI, influencing academic circles and the broader public understanding of this transformative technology.',
    programs: [
      "The Pursuit of Machine Learning",
      "The Crossroads Between AI and Space",
      "The Challenge & Promise of Artificial Intelligence",
    ],
    fee: "$25k to $50k plus travel",
    location: "California, United States",
    linkedin: "https://www.linkedin.com/in/pnorvig/",
    website: "https://norvig.com/",
    email: "peter@norvig.com",
    contact: "Direct",
    listed: true,
    expertise: ["Artificial Intelligence", "Machine Learning", "Search Algorithms", "AI Education"],
    industries: ["Technology", "Education", "Research"],
    ranking: 100,
  },
  {
    slug: "cassie-kozyrkov",
    name: "Cassie Kozyrkov",
    title: "Former Google Chief Decision Scientist",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Cassie Kozyrkov was Google's first Chief Decision Scientist, where she advised executives on AI strategy and decision intelligence. She's an expert in making AI accessible to business leaders and has been instrumental in democratizing data science and machine learning across organizations. Kozyrkov is known for her ability to translate complex AI concepts into actionable business strategies.",
    programs: [
      "AI Strategy for Business Leaders",
      "Decision Intelligence in the Age of AI",
      "Responsible AI Implementation",
      "Data-Driven Decision Making at Scale",
    ],
    fee: "$45k-$70k",
    location: "Miami, Florida",
    linkedin: "https://www.linkedin.com/in/kozyrkov/",
    email: "speaking@kozyr.com",
    contact: "Peter",
    listed: true,
    expertise: ["AI Strategy", "Decision Intelligence", "Data Science", "Business AI"],
    industries: ["Technology", "Finance", "Healthcare", "Consulting"],
    ranking: 92,
  },
  {
    slug: "rana-el-kaliouby",
    name: "Rana el Kaliouby",
    title: "Co-Founder of Affectiva (Emotion AI)",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Dr. Rana el Kaliouby is a pioneer in Emotion AI and co-founder of Affectiva, the leading emotion recognition technology company. She holds a PhD from Cambridge University and has been recognized as one of the most influential women in AI. Her work focuses on humanizing technology through emotion recognition and has applications across automotive, advertising, and healthcare industries.",
    programs: [
      "The Future of Emotion AI",
      "Humanizing Technology Through Emotional Intelligence",
      "Computer Vision and Facial Recognition",
      "Building AI Startups That Matter",
    ],
    fee: "Please Inquire",
    location: "Boston, MA",
    linkedin: "https://www.linkedin.com/in/kaliouby/",
    email: "kaliouby@smarteye.ai",
    contact: "Adam",
    listed: true,
    expertise: ["Emotion AI", "Computer Vision", "Facial Recognition", "AI Startups"],
    industries: ["Automotive", "Healthcare", "Advertising", "Technology"],
    ranking: 90,
  },
  {
    slug: "allie-k-miller",
    name: "Allie Miller",
    title: "Former Head of Machine Learning Business Development at Amazon",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Allie Miller is a leading AI strategist and former Amazon executive who was the youngest woman to work on IBM Watson. She has been instrumental in scaling AI initiatives across Fortune 500 companies and is a passionate advocate for diversity in AI. Miller combines technical expertise with business acumen to help organizations successfully implement AI strategies.",
    programs: [
      "AI Strategy for Enterprise Scale",
      "Machine Learning Business Applications",
      "Diversity and Inclusion in AI",
      "Building AI-First Organizations",
    ],
    fee: "$70k",
    location: "New York City",
    linkedin: "https://www.linkedin.com/in/alliekmiller/",
    email: "hello@alliekmiller.com",
    contact: "Adam",
    listed: true,
    expertise: ["AI Strategy", "Machine Learning", "Business Development", "AI Diversity"],
    industries: ["Technology", "Finance", "Retail", "Healthcare"],
    ranking: 88,
  },
  {
    slug: "dag-kittlaus",
    name: "Dag Kittlaus",
    title: "Co-Founder of Siri & AI Entrepreneur",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Dag Kittlaus is the co-founder of Siri and a pioneering AI entrepreneur. He has been instrumental in developing conversational AI technologies and continues to work on advancing AI applications and entrepreneurship.",
    programs: [
      "The Evolution of Conversational AI",
      "AI Entrepreneurship and Innovation",
      "Building AI Companies",
      "The Future of Voice Technology",
    ],
    fee: "$50-$70k",
    location: "Silicon Valley",
    email: "dag@sirifounder.com",
    contact: "Direct",
    listed: true,
    expertise: ["Conversational AI", "AI Entrepreneurship", "Voice Technology", "AI Innovation"],
    industries: ["Technology", "Startups", "AI", "Consumer Electronics"],
    ranking: 85,
  },
  {
    slug: "david-eagleman",
    name: "David Eagleman",
    title: "Neuroscientist & AI-Brain Interface Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "David Eagleman is a renowned neuroscientist and AI-brain interface expert who explores the intersection of neuroscience and artificial intelligence. He has extensive experience in brain research and the development of brain-computer interfaces.",
    programs: [
      "Neuroscience and AI",
      "Brain-Computer Interfaces",
      "The Future of Human-AI Integration",
      "Neurotechnology and AI",
    ],
    fee: "$50k-$75k",
    location: "Stanford, CA",
    email: "david@neuroscienceai.com",
    contact: "Direct",
    listed: true,
    expertise: ["Neuroscience", "Brain-Computer Interfaces", "Neurotechnology", "AI-Brain Integration"],
    industries: ["Neuroscience", "Healthcare", "Technology", "Research"],
    ranking: 85,
  },
  {
    slug: "luc-julia",
    name: "Dr. Luc Julia",
    title: "Co-Creator of Siri & AI Innovation Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Dr. Luc Julia is the co-creator of Siri and a leading AI innovation expert. He has been instrumental in developing conversational AI technologies and continues to work on advancing AI applications across various industries.",
    programs: [
      "The History and Future of Conversational AI",
      "AI Innovation and Development",
      "Voice Technology and Natural Language Processing",
      "Building AI Systems That Understand Humans",
    ],
    fee: "$50-$70k",
    location: "Paris, France",
    email: "luc@siricocreator.com",
    contact: "Direct",
    listed: true,
    expertise: ["Conversational AI", "Voice Technology", "AI Innovation", "Natural Language Processing"],
    industries: ["Technology", "AI", "Consumer Electronics", "Innovation"],
    ranking: 83,
  },
  {
    slug: "charlene-li",
    name: "Charlene Li",
    title: "Digital Transformation Expert & Former Forrester VP",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Charlene Li is a digital transformation expert, former Forrester VP, and bestselling author on leadership and technology. She is the founder of Altimeter Group and has advised Fortune 500 companies on digital strategy and AI implementation. Li is recognized as one of the most influential voices in digital transformation and future of work.",
    programs: [
      "Digital Transformation Leadership",
      "AI and the Future of Work",
      "Technology Strategy for Executives",
      "Leading Change in Digital Organizations",
    ],
    fee: "$35k US, $52.5k International",
    location: "San Francisco (SFO)",
    linkedin: "https://www.linkedin.com/in/charleneli/",
    website: "https://charleneli.com/",
    email: "charlene@charleneli.com",
    contact: "Jeremiah Owyang",
    listed: true,
    expertise: ["Digital Transformation", "AI Leadership", "Future of Work", "Technology Strategy"],
    industries: ["Technology", "Finance", "Consulting", "Media"],
    ranking: 80,
  },
  {
    slug: "ashley-tarver",
    name: "Ashley Tarver",
    title: "Data & AI Cloud Evangelist at Microsoft",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Ashley Tarver is a leading AI technology evangelist and entrepreneur who works with Microsoft's largest Silicon Valley customers to shape the future of artificial intelligence implementation. As a trusted advisor to senior executives, he guides Fortune 500 companies in deploying AI and machine learning solutions across diverse industries. Known for his exceptional ability to translate complex AI concepts into actionable business strategies, Ashley brings hands-on experience from the frontlines of the AI revolution.",
    programs: [
      "Practical adoption of AI use-cases",
      "Scaling impact Hi-Tech has on businesses",
      "Fast-Wins for AI with customers and businesses",
    ],
    fee: "Please Inquire",
    location: "San Francisco, California",
    linkedin: "https://www.linkedin.com/in/ashley-tarver/",
    email: "ashley@microsoft.com",
    contact: "Direct",
    listed: true,
    expertise: ["AI Implementation", "Enterprise Technology", "Business Strategy", "Technology Evangelism"],
    industries: ["Technology", "Enterprise", "Startups", "Consulting"],
    ranking: 78,
  },
  {
    slug: "vandi-verma",
    name: "Vandi Verma",
    title: "NASA JPL Robotics & AI Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Vandi Verma is a robotics and AI expert at NASA's Jet Propulsion Laboratory, where she works on autonomous systems for space exploration. She has been instrumental in developing AI systems for Mars rovers and other space missions.",
    programs: [
      "AI and Robotics in Space Exploration",
      "Autonomous Systems and Decision Making",
      "AI for Extreme Environments",
      "The Future of Space Technology",
    ],
    fee: "$40k-$60k",
    location: "Los Angeles, CA",
    email: "vandi@jpl.nasa.gov",
    contact: "NASA",
    listed: true,
    expertise: ["Space Robotics", "Autonomous Systems", "AI in Space", "Robotics Engineering"],
    industries: ["Aerospace", "Government", "Research", "Technology"],
    ranking: 75,
  },
  {
    slug: "joanna-bryson",
    name: "Prof. Joanna Bryson, PhD",
    title: "AI Ethics Researcher & Professor",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Professor Joanna Bryson is a leading AI ethics researcher and professor at the Hertie School in Berlin. She has been at the forefront of AI governance and ethics discussions, advising governments and organizations on responsible AI development. Bryson's work focuses on the societal implications of AI and ensuring technology serves humanity.",
    programs: [
      "AI Ethics and Governance",
      "Responsible AI Development",
      "AI Policy and Regulation",
      "The Social Impact of Artificial Intelligence",
    ],
    fee: "Academic rates available",
    location: "Berlin, Germany",
    linkedin: "https://www.linkedin.com/in/bryson/",
    email: "Bryson@hertie-school.org",
    contact: "Peter",
    listed: true,
    expertise: ["AI Ethics", "AI Governance", "Technology Policy", "Academic Research"],
    industries: ["Academia", "Government", "Policy", "Research"],
    ranking: 72,
  },
  {
    slug: "maya-ackerman",
    name: "Maya Ackerman",
    title: "AI Creativity & Computational Creativity Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Maya Ackerman is an AI creativity and computational creativity expert who explores how artificial intelligence can enhance and augment human creativity. She specializes in AI applications in creative industries and computational creativity research.",
    programs: [
      "AI and Computational Creativity",
      "The Future of Creative AI",
      "AI in Creative Industries",
      "Human-AI Creative Collaboration",
    ],
    fee: "$35k-$50k",
    location: "San Jose, CA",
    email: "maya@aicreative.com",
    contact: "Direct",
    listed: true,
    expertise: ["Computational Creativity", "AI Creativity", "Creative AI", "Human-AI Collaboration"],
    industries: ["Creative Industries", "Technology", "Entertainment", "Media"],
    ranking: 70,
  },
  {
    slug: "shafi-ahmed",
    name: "Shafi Ahmed",
    title: "Digital Health & AI in Surgery Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Shafi Ahmed is a pioneering surgeon and digital health expert who specializes in the application of AI and emerging technologies in healthcare and surgery. He is known for his work in virtual reality surgery and AI-assisted medical procedures.",
    programs: [
      "AI in Surgery and Healthcare",
      "Digital Health Innovation",
      "Virtual Reality in Medicine",
      "The Future of Medical Technology",
    ],
    fee: "$45k-$65k",
    location: "London, UK",
    email: "shafi@digitalsurgery.com",
    contact: "Direct",
    listed: true,
    expertise: ["AI in Healthcare", "Digital Surgery", "Medical Technology", "Virtual Reality"],
    industries: ["Healthcare", "Medical Devices", "Surgery", "Digital Health"],
    ranking: 70,
  },
  {
    slug: "nancy-xu",
    name: "Nancy Xu",
    title: "AI Product Manager & Technology Leader",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Nancy Xu is an experienced AI product manager and technology leader who specializes in bringing AI products from concept to market. She has extensive experience in product development, user experience design, and AI implementation across various industries.",
    programs: [
      "AI Product Development and Strategy",
      "Building User-Centric AI Products",
      "AI Product Management Best Practices",
      "Technology Leadership in AI Companies",
    ],
    fee: "$30k-$45k",
    location: "Silicon Valley",
    email: "nancy@aiproducts.com",
    contact: "Direct",
    listed: true,
    expertise: ["AI Product Management", "Product Strategy", "User Experience", "Technology Leadership"],
    industries: ["Technology", "Software", "Startups", "Product Development"],
    ranking: 65,
  },
  {
    slug: "chris-yeh",
    name: "Chris Yeh",
    title: "AI Entrepreneur & Scaling Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Chris Yeh is an AI entrepreneur and scaling expert who helps companies grow and scale their AI initiatives. He is the co-author of 'Blitzscaling' and has extensive experience in building and scaling technology companies.",
    programs: [
      "Scaling AI Companies and Initiatives",
      "AI Entrepreneurship and Innovation",
      "Blitzscaling in the AI Era",
      "Building High-Growth AI Businesses",
    ],
    fee: "$40k-$60k",
    location: "Silicon Valley",
    email: "chris@blitzscaling.com",
    contact: "Direct",
    listed: true,
    expertise: ["AI Entrepreneurship", "Business Scaling", "Technology Strategy", "Innovation"],
    industries: ["Technology", "Startups", "Venture Capital", "Entrepreneurship"],
    ranking: 65,
  },
  {
    slug: "ben-parr",
    name: "Ben Parr",
    title: "AI Entrepreneur & Technology Journalist",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Ben Parr is an AI entrepreneur and technology journalist who has been covering the AI industry and building AI companies. He is the co-founder of Octane AI and has extensive experience in AI entrepreneurship and technology journalism.",
    programs: [
      "AI Entrepreneurship and Innovation",
      "Building AI Companies",
      "Technology Trends and AI",
      "AI in E-commerce and Marketing",
    ],
    fee: "$35k-$50k",
    location: "San Francisco",
    email: "ben@octaneai.com",
    contact: "Direct",
    listed: true,
    expertise: ["AI Entrepreneurship", "Technology Journalism", "E-commerce AI", "AI Innovation"],
    industries: ["Technology", "E-commerce", "Media", "Startups"],
    ranking: 63,
  },
  {
    slug: "max-sills",
    name: "Max Sills",
    title: "AI Startup Advisor & Technology Investor",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Max Sills is an AI startup advisor and technology investor who helps early-stage companies navigate the AI landscape. He has extensive experience in AI venture capital and provides strategic guidance to AI startups and entrepreneurs.",
    programs: [
      "AI Startup Strategy and Funding",
      "Venture Capital in AI",
      "Building Successful AI Companies",
      "AI Investment Trends and Opportunities",
    ],
    fee: "$35k-$50k",
    location: "Silicon Valley",
    email: "max@aiventures.com",
    contact: "Direct",
    listed: true,
    expertise: ["AI Startups", "Venture Capital", "Technology Investment", "Entrepreneurship"],
    industries: ["Venture Capital", "Startups", "Technology", "Investment"],
    ranking: 60,
  },
  {
    slug: "ryan-pamplin",
    name: "Ryan Pamplin",
    title: "AI Marketing & Customer Experience Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Ryan Pamplin is an AI marketing and customer experience expert who helps companies leverage artificial intelligence to enhance customer relationships and drive business growth. He specializes in AI-powered marketing automation and personalization.",
    programs: [
      "AI-Powered Marketing and Personalization",
      "Customer Experience in the AI Era",
      "Marketing Automation and AI",
      "Data-Driven Customer Insights",
    ],
    fee: "$30k-$45k",
    location: "Chicago, IL",
    email: "ryan@aimarketing.com",
    contact: "Direct",
    listed: true,
    expertise: ["AI Marketing", "Customer Experience", "Marketing Automation", "Personalization"],
    industries: ["Marketing", "Retail", "E-commerce", "Technology"],
    ranking: 51,
  },
  {
    slug: "divya-chander",
    name: "Divya Chander",
    title: "Neuroscience & AI in Medicine Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Divya Chander is a neuroscience and AI in medicine expert who specializes in the application of artificial intelligence in neuroscience and medical practice. She has extensive experience in medical AI research and neurotechnology.",
    programs: [
      "AI in Neuroscience and Medicine",
      "Neurotechnology and AI",
      "Medical AI Research and Applications",
      "The Future of Neuroscience Technology",
    ],
    fee: "$40k-$60k",
    location: "Stanford, CA",
    email: "divya@neuroscienceai.com",
    contact: "Direct",
    listed: true,
    expertise: ["Neuroscience AI", "Medical AI", "Neurotechnology", "Medical Research"],
    industries: ["Healthcare", "Neuroscience", "Medical Research", "Technology"],
    ranking: 55,
  },
  {
    slug: "chris-duffey",
    name: "Chris Duffey",
    title: "AI Creative & Marketing Innovation Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Chris Duffey is an AI creative and marketing innovation expert who explores the intersection of artificial intelligence and creativity. He helps brands and organizations understand how AI can enhance creative processes and marketing effectiveness.",
    programs: [
      "AI and Creativity in Marketing",
      "The Future of Creative AI",
      "AI-Powered Brand Innovation",
      "Creative Technology and AI",
    ],
    fee: "$35k-$50k",
    location: "Los Angeles, CA",
    email: "chris@aicreative.com",
    contact: "Direct",
    listed: true,
    expertise: ["AI Creativity", "Marketing Innovation", "Creative Technology", "Brand Strategy"],
    industries: ["Marketing", "Advertising", "Creative Industries", "Technology"],
    ranking: 55,
  },
  {
    slug: "sounil-yu",
    name: "Sounil Yu",
    title: "Cybersecurity & AI Security Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Sounil Yu is a leading cybersecurity expert specializing in AI security and the intersection of artificial intelligence and cybersecurity. He helps organizations understand and mitigate security risks associated with AI systems and develop secure AI implementations.",
    programs: [
      "AI Security and Cybersecurity",
      "Securing AI Systems and Models",
      "AI-Powered Cyber Threats",
      "Building Secure AI Infrastructure",
    ],
    fee: "$40k-$55k",
    location: "New York",
    email: "sounil@aisecurity.com",
    contact: "Direct",
    listed: true,
    expertise: ["AI Security", "Cybersecurity", "Risk Management", "Security Architecture"],
    industries: ["Cybersecurity", "Technology", "Finance", "Government"],
    ranking: 52,
  },
  {
    slug: "oak-felder",
    name: "Oak Felder",
    title: "AI Music & Creative Technology Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Oak Felder is an AI music and creative technology expert who explores the intersection of artificial intelligence and music production. He has extensive experience in music technology and AI applications in creative industries.",
    programs: [
      "AI in Music Production and Creation",
      "Creative Technology and AI",
      "The Future of AI in Entertainment",
      "Music Technology Innovation",
    ],
    fee: "$30k-$45k",
    location: "Los Angeles, CA",
    email: "oak@aimusictech.com",
    contact: "Direct",
    listed: true,
    expertise: ["AI Music", "Creative Technology", "Music Production", "Entertainment AI"],
    industries: ["Music", "Entertainment", "Creative Industries", "Technology"],
    ranking: 53,
  },
  {
    slug: "david-ewing-duncan",
    name: "David Ewing Duncan",
    title: "Biotech & AI Futurist, Author",
    image: "/placeholder.svg?height=400&width=400",
    bio: "David Ewing Duncan is a renowned author, journalist, and futurist specializing in biotechnology and artificial intelligence. He has written several bestselling books on the intersection of technology and human health, and is a frequent speaker on the future of medicine, longevity, and AI applications in healthcare.",
    programs: [
      "The Future of Human Longevity",
      "AI in Biotechnology and Medicine",
      "Genetic Engineering and Society",
      "Technology and Human Enhancement",
    ],
    fee: "$30k-$45k",
    location: "San Francisco",
    email: "speaking@davidduncan.com",
    contact: "Direct",
    listed: true,
    expertise: ["Biotechnology", "AI in Healthcare", "Longevity", "Genetic Engineering"],
    industries: ["Healthcare", "Biotechnology", "Pharmaceuticals", "Research"],
    ranking: 50,
  },
  {
    slug: "lital-marom",
    name: "Lital Marom",
    title: "AI Chatbots & Conversational AI Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Lital Marom is an AI chatbots and conversational AI expert who specializes in developing intelligent conversational systems. She has extensive experience in chatbot development and conversational AI applications across various industries.",
    programs: [
      "Chatbots and Conversational AI",
      "Building Intelligent Conversational Systems",
      "AI Customer Service and Support",
      "The Future of Conversational Interfaces",
    ],
    fee: "$30k-$45k",
    location: "Tel Aviv, Israel",
    email: "lital@conversationalai.com",
    contact: "Direct",
    listed: true,
    expertise: ["Conversational AI", "Chatbots", "AI Customer Service", "Natural Language Processing"],
    industries: ["Technology", "Customer Service", "E-commerce", "Software"],
    ranking: 49,
  },
  {
    slug: "katie-mcmahon",
    name: "Katie McMahon",
    title: "AI Strategy & Innovation Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Katie McMahon is a leading AI strategy and innovation expert who helps organizations navigate the complexities of artificial intelligence implementation. With extensive experience in technology consulting and AI transformation, she specializes in helping companies develop comprehensive AI strategies that drive business value.",
    programs: [
      "AI Strategy for Business Leaders",
      "Innovation Management in the AI Era",
      "Digital Transformation and AI",
      "Building AI-Ready Organizations",
    ],
    fee: "$30k-$45k",
    location: "New York",
    email: "katie@aimcmahon.com",
    contact: "Direct",
    listed: true,
    expertise: ["AI Strategy", "Innovation Management", "Digital Transformation", "Business AI"],
    industries: ["Technology", "Consulting", "Finance", "Healthcare"],
    ranking: 48,
  },
  {
    slug: "dan-russell",
    name: "Dan Russell",
    title: "Google Search & AI Research Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Dan Russell is a Google search and AI research expert who has been instrumental in developing search technologies and AI applications. He specializes in information retrieval, search algorithms, and AI-powered information systems.",
    programs: [
      "Search Technology and AI",
      "Information Retrieval Systems",
      "AI-Powered Search and Discovery",
      "The Future of Information Access",
    ],
    fee: "$35k-$50k",
    location: "Mountain View, CA",
    email: "dan@googlesearch.com",
    contact: "Google",
    listed: true,
    expertise: ["Search Technology", "Information Retrieval", "AI Research", "Google Technologies"],
    industries: ["Technology", "Search", "Information Systems", "AI"],
    ranking: 45,
  },
  {
    slug: "vicki-reyzelman",
    name: "Vicki Reyzelman",
    title: "AI Healthcare & Medical Technology Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Vicki Reyzelman is an AI healthcare and medical technology expert who specializes in the application of artificial intelligence in healthcare settings. She has extensive experience in medical AI implementation and healthcare technology innovation.",
    programs: [
      "AI in Healthcare and Medicine",
      "Medical Technology Innovation",
      "Healthcare AI Implementation",
      "Digital Health Transformation",
    ],
    fee: "$35k-$50k",
    location: "San Francisco",
    email: "vicki@healthcareai.com",
    contact: "Direct",
    listed: true,
    expertise: ["Healthcare AI", "Medical Technology", "Digital Health", "Healthcare Innovation"],
    industries: ["Healthcare", "Medical Technology", "Digital Health", "Pharmaceuticals"],
    ranking: 45,
  },
  {
    slug: "zach-rattner",
    name: "Zach Rattner",
    title: "AI Gaming & Interactive Technology Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Zach Rattner is an AI gaming and interactive technology expert who specializes in the application of artificial intelligence in gaming and interactive entertainment. He has extensive experience in game AI and interactive technology development.",
    programs: [
      "AI in Gaming and Interactive Entertainment",
      "Game AI Development",
      "Interactive Technology Innovation",
      "The Future of AI in Gaming",
    ],
    fee: "$35k-$50k",
    location: "San Francisco",
    email: "zach@gamingai.com",
    contact: "Direct",
    listed: true,
    expertise: ["Gaming AI", "Interactive Technology", "Game Development", "Entertainment Technology"],
    industries: ["Gaming", "Entertainment", "Technology", "Interactive Media"],
    ranking: 50,
  },
  {
    slug: "robin-farmanfarmaian",
    name: "Robin Farmanfarmaian",
    title: "Digital Health & AI Innovation Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Robin Farmanfarmaian is a digital health and AI innovation expert who helps healthcare organizations leverage emerging technologies. She is an author, speaker, and consultant specializing in healthcare technology and AI applications in medicine.",
    programs: [
      "Digital Health Innovation and AI",
      "Healthcare Technology Transformation",
      "AI Applications in Patient Care",
      "The Future of Healthcare Technology",
    ],
    fee: "$35k-$50k",
    location: "Silicon Valley",
    email: "robin@digitalhealthai.com",
    contact: "Direct",
    listed: true,
    expertise: ["Digital Health", "Healthcare AI", "Medical Innovation", "Healthcare Technology"],
    industries: ["Healthcare", "Digital Health", "Medical Devices", "Technology"],
    ranking: 43,
  },
  {
    slug: "roman-yampolskiy",
    name: "Roman Yampolskiy",
    title: "AI Safety & Security Researcher",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Roman Yampolskiy is a leading AI safety and security researcher who focuses on the risks and challenges associated with artificial intelligence. He is a professor and researcher specializing in AI safety, security, and the long-term implications of AI development.",
    programs: [
      "AI Safety and Security Challenges",
      "The Risks of Artificial Intelligence",
      "AI Alignment and Control Problems",
      "Long-term AI Safety Research",
    ],
    fee: "$30k-$45k",
    location: "Louisville, KY",
    email: "roman@aisafety.edu",
    contact: "University",
    listed: true,
    expertise: ["AI Safety", "AI Security", "AI Risk Assessment", "AI Research"],
    industries: ["Academia", "Research", "Government", "Technology"],
    ranking: 39,
  },
  {
    slug: "sonal-gupta",
    name: "Sonal Gupta",
    title: "AI Research Scientist & NLP Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Sonal Gupta is a leading AI research scientist specializing in natural language processing and conversational AI. With extensive experience in developing AI systems that understand and generate human language, she has contributed to breakthrough advances in NLP and machine learning applications.",
    programs: [
      "Natural Language Processing and AI",
      "Conversational AI Systems",
      "Machine Learning Research",
      "The Future of Human-AI Communication",
    ],
    fee: "$35k-$50k",
    location: "Silicon Valley",
    email: "sonal@nlpresearch.com",
    contact: "Direct",
    listed: true,
    expertise: ["Natural Language Processing", "Conversational AI", "Machine Learning", "AI Research"],
    industries: ["Technology", "Research", "Software", "AI"],
    ranking: 45,
  },
  {
    slug: "brad-templeton",
    name: "Brad Templeton",
    title: "Autonomous Vehicles & AI Transportation Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Brad Templeton is an autonomous vehicles and AI transportation expert who has been at the forefront of self-driving car technology. He has extensive experience in transportation AI and helps organizations understand the future of mobility and autonomous systems.",
    programs: [
      "Autonomous Vehicles and Self-Driving Cars",
      "AI in Transportation and Mobility",
      "The Future of Transportation Technology",
      "Smart Cities and Autonomous Systems",
    ],
    fee: "$35k-$50k",
    location: "Silicon Valley",
    email: "brad@autonomousvehicles.com",
    contact: "Direct",
    listed: true,
    expertise: ["Autonomous Vehicles", "Transportation AI", "Self-Driving Technology", "Mobility Innovation"],
    industries: ["Automotive", "Transportation", "Technology", "Smart Cities"],
    ranking: 37,
  },
  {
    slug: "alex-salkever",
    name: "Alex Salkever",
    title: "Technology Author & AI Business Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Alex Salkever is a technology author and business expert specializing in artificial intelligence and digital transformation. He has written extensively about the business implications of AI and helps organizations understand how to leverage emerging technologies for competitive advantage.",
    programs: [
      "AI Business Strategy and Implementation",
      "Digital Transformation Leadership",
      "Technology Trends and Business Impact",
      "The Future of Work in the AI Era",
    ],
    fee: "$30k-$45k",
    location: "San Francisco",
    email: "alex@salkever.com",
    contact: "Direct",
    listed: true,
    expertise: ["AI Business Strategy", "Digital Transformation", "Technology Writing", "Business Innovation"],
    industries: ["Technology", "Media", "Consulting", "Publishing"],
    ranking: 40,
  },
  {
    slug: "stefano-bini",
    name: "Stefano Bini",
    title: "AI Healthcare & Medical Innovation Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Stefano Bini is an AI healthcare and medical innovation expert who specializes in the application of artificial intelligence in medical practice and healthcare delivery. He has extensive experience in medical AI implementation and healthcare technology innovation.",
    programs: [
      "AI in Medical Practice and Healthcare",
      "Medical Innovation and Technology",
      "Healthcare AI Implementation",
      "Digital Medicine and AI",
    ],
    fee: "$35k-$50k",
    location: "San Francisco",
    email: "stefano@medicalai.com",
    contact: "Direct",
    listed: true,
    expertise: ["Medical AI", "Healthcare Innovation", "Digital Medicine", "Medical Technology"],
    industries: ["Healthcare", "Medical Technology", "Digital Health", "Medicine"],
    ranking: 33,
  },
  {
    slug: "rafael-grossmann",
    name: "Rafael Grossmann",
    title: "Digital Surgery & AI in Medicine Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Rafael Grossmann is a digital surgery and AI in medicine expert who pioneered the use of emerging technologies in surgical practice. He is known for his innovative work in digital health and AI applications in surgery and medical education.",
    programs: [
      "Digital Surgery and AI in Medicine",
      "Innovation in Medical Technology",
      "AI Applications in Surgery",
      "The Future of Medical Practice",
    ],
    fee: "$40k-$60k",
    location: "Vermont",
    email: "rafael@digitalsurgery.com",
    contact: "Direct",
    listed: true,
    expertise: ["Digital Surgery", "Medical AI", "Surgical Innovation", "Medical Technology"],
    industries: ["Healthcare", "Surgery", "Medical Technology", "Digital Health"],
    ranking: 31,
  },
  {
    slug: "sagar-savla",
    name: "Sagar Savla",
    title: "AI Engineering & Machine Learning Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Sagar Savla is an AI engineering and machine learning expert with extensive experience in building and deploying AI systems at scale. He specializes in machine learning infrastructure, AI model optimization, and enterprise AI implementation.",
    programs: [
      "AI Engineering and Infrastructure",
      "Machine Learning at Scale",
      "AI Model Optimization and Deployment",
      "Enterprise AI Implementation",
    ],
    fee: "$35k-$50k",
    location: "San Francisco",
    email: "sagar@aiengineering.com",
    contact: "Direct",
    listed: true,
    expertise: ["AI Engineering", "Machine Learning", "AI Infrastructure", "Model Deployment"],
    industries: ["Technology", "Software", "Cloud Computing", "Enterprise"],
    ranking: 30,
  },
  {
    slug: "ben-parr",
    name: "Ben Parr",
    title: "AI Entrepreneur & Technology Journalist",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Ben Parr is an AI entrepreneur and technology journalist who has been covering the AI industry and building AI companies. He is the co-founder of Octane AI and has extensive experience in AI entrepreneurship and technology journalism.",
    programs: [
      "AI Entrepreneurship and Innovation",
      "Building AI Companies",
      "Technology Trends and AI",
      "AI in E-commerce and Marketing",
    ],
    fee: "$35k-$50k",
    location: "San Francisco",
    email: "ben@octaneai.com",
    contact: "Direct",
    listed: true,
    expertise: ["AI Entrepreneurship", "Technology Journalism", "E-commerce AI", "AI Innovation"],
    industries: ["Technology", "E-commerce", "Media", "Startups"],
    ranking: 29,
  },
  {
    slug: "simone-bianco",
    name: "Simone Bianco",
    title: "AI Research Scientist & Computer Vision Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Simone Bianco is an AI research scientist specializing in computer vision and machine learning. He has made significant contributions to the field of visual AI and has extensive experience in developing computer vision systems for various applications.",
    programs: [
      "Computer Vision and Visual AI",
      "Machine Learning Research",
      "AI Applications in Visual Recognition",
      "Deep Learning for Computer Vision",
    ],
    fee: "$35k-$50k",
    location: "Milan, Italy",
    email: "simone@visionai.com",
    contact: "Direct",
    listed: true,
    expertise: ["Computer Vision", "Machine Learning", "Visual AI", "Deep Learning"],
    industries: ["Technology", "Research", "Automotive", "Healthcare"],
    ranking: 28,
  },
  {
    slug: "larry-magid",
    name: "Larry Magid",
    title: "Technology Journalist & AI Ethics Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Larry Magid is a technology journalist and AI ethics expert who has been covering technology trends and their societal implications for decades. He specializes in technology policy, digital safety, and the ethical implications of AI development.",
    programs: [
      "AI Ethics and Digital Safety",
      "Technology Policy and Regulation",
      "The Social Impact of AI",
      "Digital Citizenship in the AI Era",
    ],
    fee: "$25k-$40k",
    location: "Silicon Valley",
    email: "larry@techpolicy.com",
    contact: "Direct",
    listed: true,
    expertise: ["Technology Journalism", "AI Ethics", "Digital Safety", "Technology Policy"],
    industries: ["Media", "Technology", "Policy", "Education"],
    ranking: 27,
  },
  {
    slug: "mike-cassidy",
    name: "Mike Cassidy",
    title: "AI Innovation & Technology Leadership Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Mike Cassidy is an AI innovation and technology leadership expert with extensive experience in building and leading technology companies. He has been involved in various AI initiatives and helps organizations develop innovation strategies.",
    programs: [
      "AI Innovation and Leadership",
      "Technology Strategy and Development",
      "Building Innovation Culture",
      "AI Technology Implementation",
    ],
    fee: "$35k-$50k",
    location: "Silicon Valley",
    email: "mike@aiinnovation.com",
    contact: "Direct",
    listed: true,
    expertise: ["AI Innovation", "Technology Leadership", "Innovation Strategy", "Technology Development"],
    industries: ["Technology", "Innovation", "Startups", "Leadership"],
    ranking: 25,
  },
  {
    slug: "max-sills",
    name: "Max Sills",
    title: "AI Startup Advisor & Technology Investor",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Max Sills is an AI startup advisor and technology investor who helps early-stage companies navigate the AI landscape. He has extensive experience in AI venture capital and provides strategic guidance to AI startups and entrepreneurs.",
    programs: [
      "AI Startup Strategy and Funding",
      "Venture Capital in AI",
      "Building Successful AI Companies",
      "AI Investment Trends and Opportunities",
    ],
    fee: "$35k-$50k",
    location: "Silicon Valley",
    email: "max@aiventures.com",
    contact: "Direct",
    listed: true,
    expertise: ["AI Startups", "Venture Capital", "Technology Investment", "Entrepreneurship"],
    industries: ["Venture Capital", "Startups", "Technology", "Investment"],
    ranking: 25,
  },
  {
    slug: "alfred-poor",
    name: "Alfred Poor",
    title: "Health Technology & AI Wearables Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Alfred Poor is a health technology and AI wearables expert who specializes in the intersection of artificial intelligence and health monitoring devices. He has extensive experience in health tech innovation and AI applications in wearable technology.",
    programs: [
      "AI in Health Technology and Wearables",
      "Health Monitoring and AI",
      "Wearable Technology Innovation",
      "The Future of Health Tech",
    ],
    fee: "$30k-$45k",
    location: "Pennsylvania",
    email: "alfred@healthtechai.com",
    contact: "Direct",
    listed: true,
    expertise: ["Health Technology", "Wearable AI", "Health Monitoring", "Medical Devices"],
    industries: ["Healthcare", "Wearable Technology", "Medical Devices", "Health Tech"],
    ranking: 23,
  },
  {
    slug: "ryan-pamplin",
    name: "Ryan Pamplin",
    title: "AI Marketing & Customer Experience Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Ryan Pamplin is an AI marketing and customer experience expert who helps companies leverage artificial intelligence to enhance customer relationships and drive business growth. He specializes in AI-powered marketing automation and personalization.",
    programs: [
      "AI-Powered Marketing and Personalization",
      "Customer Experience in the AI Era",
      "Marketing Automation and AI",
      "Data-Driven Customer Insights",
    ],
    fee: "$30k-$45k",
    location: "Chicago, IL",
    email: "ryan@aimarketing.com",
    contact: "Direct",
    listed: true,
    expertise: ["AI Marketing", "Customer Experience", "Marketing Automation", "Personalization"],
    industries: ["Marketing", "Retail", "E-commerce", "Technology"],
    ranking: 22,
  },
  {
    slug: "peter-small",
    name: "Peter Small",
    title: "AI Business Strategy & Technology Consulting Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Peter Small is an AI business strategy and technology consulting expert who helps organizations develop and implement AI strategies. He has extensive experience in technology consulting and AI business transformation.",
    programs: [
      "AI Business Strategy and Implementation",
      "Technology Consulting and AI",
      "Digital Transformation with AI",
      "AI Strategy for Business Leaders",
    ],
    fee: "$30k-$45k",
    location: "New York",
    email: "peter@aibusinessstrategy.com",
    contact: "Direct",
    listed: true,
    expertise: ["AI Business Strategy", "Technology Consulting", "Digital Transformation", "Business AI"],
    industries: ["Consulting", "Technology", "Business Strategy", "AI"],
    ranking: 21,
  },
  {
    slug: "simon-pierro",
    name: "Simon Pierro",
    title: "Digital Magic & AI Entertainment Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Simon Pierro is a digital magician and AI entertainment expert who combines magic with cutting-edge technology. He demonstrates the possibilities of AI and emerging technologies through innovative performances and presentations.",
    programs: [
      "AI and the Future of Entertainment",
      "Digital Magic and Technology",
      "Innovation Through Creative Technology",
      "Engaging Audiences with AI Demonstrations",
    ],
    fee: "$25k-$40k",
    location: "Germany/Global",
    email: "simon@digitalmagic.com",
    contact: "Direct",
    listed: true,
    expertise: ["Digital Entertainment", "AI Demonstrations", "Technology Innovation", "Creative Technology"],
    industries: ["Entertainment", "Technology", "Events", "Creative Industries"],
    ranking: 20,
  },
  {
    slug: "matthew-blakemore",
    name: "Matthew Blakemore",
    title: "AI Technology & Innovation Consultant",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Matthew Blakemore is an AI technology and innovation consultant who helps organizations navigate the AI landscape and implement innovative AI solutions. He has extensive experience in technology innovation and AI consulting.",
    programs: [
      "AI Technology Innovation",
      "AI Implementation Strategies",
      "Technology Innovation Consulting",
      "AI Transformation for Organizations",
    ],
    fee: "$30k-$45k",
    location: "London, UK",
    email: "matthew@aitechconsulting.com",
    contact: "Direct",
    listed: true,
    expertise: ["AI Technology", "Innovation Consulting", "Technology Strategy", "AI Implementation"],
    industries: ["Technology", "Consulting", "Innovation", "AI"],
    ranking: 19,
  },
  {
    slug: "chris-jones",
    name: "Chris Jones",
    title: "AI Technology & Innovation Consultant",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Chris Jones is an AI technology and innovation consultant who helps organizations implement artificial intelligence solutions and develop innovation strategies. He has extensive experience in technology consulting and AI transformation across various industries.",
    programs: [
      "AI Implementation and Strategy",
      "Technology Innovation Consulting",
      "Digital Transformation with AI",
      "Building AI-Driven Organizations",
    ],
    fee: "$30k-$45k",
    location: "Austin, TX",
    email: "chris@aitechconsulting.com",
    contact: "Direct",
    listed: true,
    expertise: ["AI Consulting", "Technology Innovation", "Digital Transformation", "Strategy Development"],
    industries: ["Technology", "Consulting", "Manufacturing", "Finance"],
    ranking: 10,
  },
  {
    slug: "shawn-flynn",
    name: "Shawn Flynn",
    title: "AI Investment & Silicon Valley Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Shawn Flynn is an AI investment expert and Silicon Valley insider who provides insights into AI investment trends and startup ecosystems. He helps investors and entrepreneurs navigate the AI landscape and identify promising opportunities.",
    programs: [
      "AI Investment Trends and Opportunities",
      "Silicon Valley AI Ecosystem",
      "AI Startup Evaluation and Strategy",
      "Technology Investment Analysis",
    ],
    fee: "$35k-$50k",
    location: "Silicon Valley",
    email: "shawn@aiinvestments.com",
    contact: "Direct",
    listed: true,
    expertise: ["AI Investment", "Venture Capital", "Startup Ecosystem", "Technology Analysis"],
    industries: ["Venture Capital", "Investment", "Technology", "Startups"],
    ranking: 15,
  },
  {
    slug: "chris-duffey",
    name: "Chris Duffey",
    title: "AI Creative & Marketing Innovation Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Chris Duffey is an AI creative and marketing innovation expert who explores the intersection of artificial intelligence and creativity. He helps brands and organizations understand how AI can enhance creative processes and marketing effectiveness.",
    programs: [
      "AI and Creativity in Marketing",
      "The Future of Creative AI",
      "AI-Powered Brand Innovation",
      "Creative Technology and AI",
    ],
    fee: "$35k-$50k",
    location: "Los Angeles, CA",
    email: "chris@aicreative.com",
    contact: "Direct",
    listed: true,
    expertise: ["AI Creativity", "Marketing Innovation", "Creative Technology", "Brand Strategy"],
    industries: ["Marketing", "Advertising", "Creative Industries", "Technology"],
    ranking: 12,
  },
  {
    slug: "david-fajgenbaum",
    name: "David Fajgenbaum",
    title: "AI in Drug Discovery & Medical Research Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "David Fajgenbaum is an AI in drug discovery and medical research expert who specializes in using artificial intelligence to accelerate medical research and drug development. He has extensive experience in medical AI research and pharmaceutical innovation.",
    programs: [
      "AI in Drug Discovery and Development",
      "Medical Research and AI",
      "Pharmaceutical Innovation with AI",
      "Accelerating Medical Breakthroughs with AI",
    ],
    fee: "$40k-$60k",
    location: "Philadelphia, PA",
    email: "david@drugdiscoveryai.com",
    contact: "Direct",
    listed: true,
    expertise: ["Drug Discovery AI", "Medical Research", "Pharmaceutical AI", "Medical Innovation"],
    industries: ["Pharmaceuticals", "Medical Research", "Healthcare", "Biotechnology"],
    ranking: 11,
  },
  {
    slug: "dan-lohrmann",
    name: "Dan Lohrmann",
    title: "Cybersecurity & AI Security Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Dan Lohrmann is a leading cybersecurity expert specializing in AI security and government technology. He has extensive experience in cybersecurity strategy and helps organizations understand the security implications of AI adoption.",
    programs: [
      "AI Security and Cybersecurity Strategy",
      "Government Technology and AI",
      "Cybersecurity Risk Management",
      "Securing AI Systems and Infrastructure",
    ],
    fee: "$35k-$50k",
    location: "Michigan",
    email: "dan@cybersecurityai.com",
    contact: "Direct",
    listed: true,
    expertise: ["Cybersecurity", "AI Security", "Government Technology", "Risk Management"],
    industries: ["Government", "Cybersecurity", "Technology", "Public Sector"],
    ranking: 10,
  },
  {
    slug: "oak-felder",
    name: "Oak Felder",
    title: "AI Music & Creative Technology Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Oak Felder is an AI music and creative technology expert who explores the intersection of artificial intelligence and music production. He has extensive experience in music technology and AI applications in creative industries.",
    programs: [
      "AI in Music Production and Creation",
      "Creative Technology and AI",
      "The Future of AI in Entertainment",
      "Music Technology Innovation",
    ],
    fee: "$30k-$45k",
    location: "Los Angeles, CA",
    email: "oak@aimusictech.com",
    contact: "Direct",
    listed: true,
    expertise: ["AI Music", "Creative Technology", "Music Production", "Entertainment AI"],
    industries: ["Music", "Entertainment", "Creative Industries", "Technology"],
    ranking: 9,
  },
  {
    slug: "tatyana-mamut",
    name: "Tatyana Mamut",
    title: "AI Product Strategy & Technology Leadership Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Tatyana Mamut is an AI product strategy and technology leadership expert with extensive experience in building and scaling AI products. She has held senior leadership positions at major technology companies and specializes in AI product development and strategy.",
    programs: [
      "AI Product Strategy and Development",
      "Technology Leadership in AI",
      "Building Scalable AI Products",
      "AI Product Management Excellence",
    ],
    fee: "$40k-$60k",
    location: "San Francisco",
    email: "tatyana@aiproductstrategy.com",
    contact: "Direct",
    listed: true,
    expertise: ["AI Product Strategy", "Technology Leadership", "Product Development", "AI Innovation"],
    industries: ["Technology", "Software", "Product Management", "AI"],
    ranking: 8,
  },
  {
    slug: "rene-caissie",
    name: "Rene Caissie",
    title: "AI Accessibility & Inclusive Technology Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Rene Caissie is an AI accessibility and inclusive technology expert who specializes in making artificial intelligence accessible to people with disabilities. He has extensive experience in accessibility technology and inclusive AI design.",
    programs: [
      "AI Accessibility and Inclusive Design",
      "Technology for People with Disabilities",
      "Inclusive AI Development",
      "Accessibility in the AI Era",
    ],
    fee: "$30k-$45k",
    location: "Canada",
    email: "rene@accessibleai.com",
    contact: "Direct",
    listed: true,
    expertise: ["AI Accessibility", "Inclusive Technology", "Disability Technology", "Accessible Design"],
    industries: ["Technology", "Accessibility", "Non-profit", "Education"],
    ranking: 7,
  },
  {
    slug: "lital-marom",
    name: "Lital Marom",
    title: "AI Chatbots & Conversational AI Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Lital Marom is an AI chatbots and conversational AI expert who specializes in developing intelligent conversational systems. She has extensive experience in chatbot development and conversational AI applications across various industries.",
    programs: [
      "Chatbots and Conversational AI",
      "Building Intelligent Conversational Systems",
      "AI Customer Service and Support",
      "The Future of Conversational Interfaces",
    ],
    fee: "$30k-$45k",
    location: "Tel Aviv, Israel",
    email: "lital@conversationalai.com",
    contact: "Direct",
    listed: true,
    expertise: ["Conversational AI", "Chatbots", "AI Customer Service", "Natural Language Processing"],
    industries: ["Technology", "Customer Service", "E-commerce", "Software"],
    ranking: 5,
  },
  {
    slug: "paolo-privitera",
    name: "Paolo Privitera",
    title: "AI Research & Innovation Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Paolo Privitera is an AI research and innovation expert who specializes in applied AI research and technology innovation. He has extensive experience in developing AI solutions for various industries and applications.",
    programs: [
      "Applied AI Research and Development",
      "AI Innovation Strategies",
      "Technology Research and Development",
      "AI Applications Across Industries",
    ],
    fee: "$35k-$50k",
    location: "Europe",
    email: "paolo@airesearch.com",
    contact: "Direct",
    listed: true,
    expertise: ["AI Research", "Technology Innovation", "Applied AI", "Research Development"],
    industries: ["Research", "Technology", "Innovation", "Academia"],
    ranking: 4,
  },
  {
    slug: "zach-rattner",
    name: "Zach Rattner",
    title: "AI Gaming & Interactive Technology Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Zach Rattner is an AI gaming and interactive technology expert who specializes in the application of artificial intelligence in gaming and interactive entertainment. He has extensive experience in game AI and interactive technology development.",
    programs: [
      "AI in Gaming and Interactive Entertainment",
      "Game AI Development",
      "Interactive Technology Innovation",
      "The Future of AI in Gaming",
    ],
    fee: "$35k-$50k",
    location: "San Francisco",
    email: "zach@gamingai.com",
    contact: "Direct",
    listed: true,
    expertise: ["Gaming AI", "Interactive Technology", "Game Development", "Entertainment Technology"],
    industries: ["Gaming", "Entertainment", "Technology", "Interactive Media"],
    ranking: 3,
  },
  {
    slug: "dan-russell",
    name: "Dan Russell",
    title: "Google Search & AI Research Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Dan Russell is a Google search and AI research expert who has been instrumental in developing search technologies and AI applications. He specializes in information retrieval, search algorithms, and AI-powered information systems.",
    programs: [
      "Search Technology and AI",
      "Information Retrieval Systems",
      "AI-Powered Search and Discovery",
      "The Future of Information Access",
    ],
    fee: "$35k-$50k",
    location: "Mountain View, CA",
    email: "dan@googlesearch.com",
    contact: "Google",
    listed: true,
    expertise: ["Search Technology", "Information Retrieval", "AI Research", "Google Technologies"],
    industries: ["Technology", "Search", "Information Systems", "AI"],
    ranking: 3,
  },
  {
    slug: "lee-sanders",
    name: "Lee Sanders",
    title: "AI Business Intelligence & Data Analytics Expert",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Lee Sanders is an AI business intelligence and data analytics expert who specializes in using artificial intelligence to enhance business decision-making. He has extensive experience in AI-powered analytics and business intelligence systems.",
    programs: [
      "AI-Powered Business Intelligence",
      "Data Analytics and AI",
      "Business Decision Making with AI",
      "AI in Business Operations",
    ],
    fee: "$30k-$45k",
    location: "Chicago, IL",
    email: "lee@aibusinessintelligence.com",
    contact: "Direct",
    listed: true,
    expertise: ["Business Intelligence", "Data Analytics", "AI Analytics", "Business AI"],
    industries: [],
  },
]

// Sort speakers by ranking (highest first)
const sortedSpeakers = speakers.sort((a, b) => b.ranking - a.ranking)

export function getAllSpeakers(): Speaker[] {
  return sortedSpeakers.filter((speaker) => speaker.listed)
}

export function getSpeakerBySlug(slug: string): Speaker | undefined {
  return speakers.find((speaker) => speaker.slug === slug)
}

export function searchSpeakers(query: string): Speaker[] {
  const lowercaseQuery = query.toLowerCase()
  return sortedSpeakers.filter(
    (speaker) =>
      speaker.listed &&
      (speaker.name.toLowerCase().includes(lowercaseQuery) ||
        speaker.title.toLowerCase().includes(lowercaseQuery) ||
        speaker.expertise.some((skill) => skill.toLowerCase().includes(lowercaseQuery)) ||
        speaker.industries.some((industry) => industry.toLowerCase().includes(lowercaseQuery)) ||
        speaker.bio.toLowerCase().includes(lowercaseQuery)),
  )
}

export function getSpeakersByIndustry(industry: string): Speaker[] {
  return sortedSpeakers.filter(
    (speaker) => speaker.listed && speaker.industries.some((ind) => ind.toLowerCase().includes(industry.toLowerCase())),
  )
}

export function getFeaturedSpeakers(count = 8): Speaker[] {
  return getAllSpeakers().slice(0, count)
}

export function getTopSpeakers(count = 6): Speaker[] {
  return getAllSpeakers().slice(0, count)
}
